import type {FastifyInstance,FastifyRequest,FastifyReply} from 'fastify';
import {pool,fail,asId,hash,token,safeError} from './core.js';
import {backupEnabled,putObjectStream,getObjectStream} from './storage.js';
import {validSample} from './live.js';
async function authorized(req:FastifyRequest){const id=asId(req.headers['x-node-id']),bearer=req.headers.authorization||'';if(!bearer.startsWith('Bearer '))fail(401,'Node credentials required');const row=(await pool.query('SELECT id FROM nodes WHERE id=$1 AND credential_hash=$2 AND deleted_at IS NULL',[id,hash(bearer.slice(7))])).rows[0];if(!row)fail(401,'Invalid node credential');return id;}
export function agentRoutes(app:FastifyInstance){
 app.post('/api/agent/enroll',async(req)=>{const b=req.body as any,id=asId(b?.nodeId),secret=String(b?.token||''),credential=token();const r=await pool.query("UPDATE nodes SET credential_hash=$1,enrollment_hash=NULL,enrollment_expires_at=NULL WHERE id=$2 AND enrollment_hash=$3 AND enrollment_expires_at>now() AND deleted_at IS NULL RETURNING id",[hash(credential),id,hash(secret)]);if(!r.rowCount)fail(401,'Expired or invalid enrollment token');return {nodeId:id,credential};});
 app.post('/api/agent/heartbeat',async(req)=>{const id=await authorized(req),b=req.body as any;await pool.query("UPDATE nodes SET status='connected',last_seen_at=now(),version=$2,usage=$3 WHERE id=$1",[id,String(b?.version||'unknown').slice(0,100),JSON.stringify(b?.usage||{})]);if(Array.isArray(b?.servers)){for(const s of b.servers.slice(0,10000)){if(typeof s.id!=='string'||!['running','stopped','failed','missing','provisioning'].includes(s.status))continue;const sample:any=validSample(s.usage)?{cpuPercent:s.usage.cpuPercent,memoryBytes:s.usage.memoryBytes,memoryLimitBytes:s.usage.memoryLimitBytes,sampledAt:new Date().toISOString()}:{};if(Number.isSafeInteger(s.diskBytes)&&s.diskBytes>=0){sample.diskBytes=s.diskBytes;sample.diskSampledAt=new Date().toISOString();}await pool.query("UPDATE servers SET observed_status=$1,usage=CASE WHEN $2::jsonb IS NULL THEN usage ELSE usage||$2::jsonb END,updated_at=now() WHERE id=$3 AND node_id=$4 AND deleted_at IS NULL AND observed_status<>'deleting'",[s.status,sample?JSON.stringify(sample):null,s.id,id]);}}return {ok:true};});
 app.get('/api/agent/jobs',async(req)=>{const id=await authorized(req),c=await pool.connect();let job:any;try{await c.query('BEGIN');job=(await c.query(`SELECT j.* FROM jobs j WHERE j.node_id=$1 AND (j.state='queued' OR (j.state='running' AND j.lease_until<now())) AND j.attempt<5 AND (j.server_id IS NULL OR NOT EXISTS (SELECT 1 FROM jobs earlier WHERE earlier.server_id=j.server_id AND earlier.id<>j.id AND earlier.state IN ('queued','running') AND (earlier.created_at<j.created_at OR (earlier.created_at=j.created_at AND earlier.id<j.id)))) ORDER BY j.created_at,j.id FOR UPDATE OF j SKIP LOCKED LIMIT 1`,[id])).rows[0];if(job){await c.query("UPDATE jobs SET state='running',attempt=attempt+1,lease_until=now()+interval '2 minutes',started_at=COALESCE(started_at,now()) WHERE id=$1",[job.id]);job.attempt++;}await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}if(!job)return {job:null};
 let server:any=null;if(job.server_id){server=(await pool.query(`SELECT s.*,t.image,t.startup,t.internal_ports,t.env,t.id AS template_id FROM servers s JOIN templates t ON t.id=s.template_id WHERE s.id=$1 AND s.deleted_at IS NULL`,[job.server_id])).rows[0];if(!server){await pool.query("UPDATE jobs SET state='failed',error='Server no longer exists',finished_at=now(),lease_until=NULL WHERE id=$1 AND state='running' AND attempt=$2",[job.id,job.attempt]);if(job.kind==='backup')await pool.query("UPDATE backups SET state='failed',error='Server no longer exists',completed_at=now() WHERE job_id=$1",[job.id]);return {job:null};}}
 const payload={...job.payload};if(['file.import','file.export'].includes(job.kind))payload.url=`/api/agent/transfers/${payload.transferId}?attempt=${job.attempt}`;try{if(job.kind==='backup'||job.kind==='restore'||job.kind==='verify-backup'){if(!backupEnabled())fail(503,'S3 backup storage is not configured');const b=(await pool.query('SELECT object_key FROM backups WHERE id=$1 AND server_id=$2',[payload.backupId,job.server_id])).rows[0];if(!b)fail(404,'Backup metadata missing');payload.url=`/api/agent/jobs/${job.id}/backup-object?attempt=${job.attempt}`;}}catch(e){const failed=await pool.query("UPDATE jobs SET state='failed',error=$1,finished_at=now(),lease_until=NULL WHERE id=$2 AND state='running' AND attempt=$3 RETURNING id",[safeError(e),job.id,job.attempt]);if(failed.rowCount&&job.kind==='backup')await pool.query("UPDATE backups SET state='failed',error=$1,completed_at=now() WHERE job_id=$2",[safeError(e),job.id]);return {job:null};}
 return {job:{id:job.id,kind:job.kind,attempt:job.attempt,payload,server:server?{id:server.id,name:server.name,memoryMb:server.memory_mb,cpuPercent:server.cpu_percent,diskMb:server.disk_mb,port:server.port,image:server.image,startup:server.startup,internalPorts:server.internal_ports,env:{...server.env,...server.variables},templateId:server.template_id}:null}};});
 const transfer=async(req:FastifyRequest,kind:'backup'|'restore'|'verify-backup',reply:FastifyReply)=>{const nodeId=await authorized(req),id=asId((req.params as any).id),attempt=Number((req.query as any)?.attempt);const job=(await pool.query("SELECT j.id,j.node_id,j.server_id,j.kind,b.object_key FROM jobs j JOIN backups b ON b.id=(j.payload->>'backupId')::uuid WHERE j.id=$1 AND j.node_id=$2 AND j.state='running' AND j.attempt=$3 AND j.lease_until>now() AND (j.kind=$4 OR ($4='restore' AND j.kind='verify-backup')) AND b.server_id=j.server_id",[id,nodeId,attempt,kind])).rows[0];if(!job)fail(409,'Backup transfer lease is invalid or expired');if(kind==='backup'){const length=Number(req.headers['content-length']);if(!Number.isSafeInteger(length)||length<1||length>10*1024*1024*1024)fail(413,'Backup must have a valid size up to 10 GiB');await putObjectStream(job.object_key,req.body as NodeJS.ReadableStream,length);return {ok:true};}const object=await getObjectStream(job.object_key);if(object.contentLength!==undefined)reply.header('content-length',object.contentLength);reply.header('content-type','application/octet-stream');return object.body;};
 app.put('/api/agent/jobs/:id/backup-object',{bodyLimit:10*1024*1024*1024},async(req,reply)=>transfer(req,'backup',reply));
 app.get('/api/agent/jobs/:id/backup-object',async(req,reply)=>transfer(req,'restore',reply));
 app.post('/api/agent/jobs/:id/renew',async(req)=>{const id=await authorized(req),b=req.body as any,r=await pool.query("UPDATE jobs SET lease_until=now()+interval '2 minutes' WHERE id=$1 AND node_id=$2 AND state='running' AND attempt=$3 AND lease_until>now() RETURNING id",[asId((req.params as any).id),id,Number(b?.attempt)]);if(!r.rowCount)fail(409,'Lease lost');return {ok:true};});
 app.post('/api/agent/jobs/:id/result',async(req)=>{const nodeId=await authorized(req),id=asId((req.params as any).id),b=req.body as any;if(typeof b?.success!=='boolean')fail(400,'success boolean required');const c=await pool.connect();try{await c.query('BEGIN');const j=(await c.query("SELECT * FROM jobs WHERE id=$1 AND node_id=$2 AND state='running' AND attempt=$3 AND lease_until>now() FOR UPDATE",[id,nodeId,Number(b?.attempt)])).rows[0];if(!j)fail(409,'Job lease lost or already finished');const error=b.success?null:safeError({message:String(b?.error||'Agent operation failed')});const result=JSON.stringify(b?.result||{});await c.query('UPDATE jobs SET state=$1,error=$2,result=$3,finished_at=now(),lease_until=NULL WHERE id=$4',[b.success?'succeeded':'failed',error,result,id]);
 if(j.kind==='backup'){await c.query('UPDATE backups SET state=$1,size_bytes=$2,error=$3,completed_at=now() WHERE job_id=$4',[b.success?'succeeded':'failed',b.success?Number(b?.result?.sizeBytes||0):null,error,id]);}
 if(j.server_id){if(j.kind==='delete'&&b.success){await c.query("UPDATE servers SET deleted_at=now(),observed_status='deleted' WHERE id=$1",[j.server_id]);await c.query('DELETE FROM allocations WHERE server_id=$1',[j.server_id]);const cancelled=await c.query("UPDATE jobs SET state='failed',error='Server was deleted',finished_at=now() WHERE server_id=$1 AND id<>$2 AND state='queued' RETURNING id",[j.server_id,j.id]);if(cancelled.rowCount)await c.query("UPDATE backups SET state='failed',error='Server was deleted',completed_at=now() WHERE job_id=ANY($1::uuid[])",[cancelled.rows.map(x=>x.id)]);}
 else if(j.kind==='create'||j.kind==='start'||j.kind==='restart'||j.kind==='reinstall'||j.kind==='configure'||j.kind==='restore'){await c.query("UPDATE servers SET observed_status=$1 WHERE id=$2 AND observed_status<>'deleting'",[b.success?'running':'failed',j.server_id]);}
 else if(j.kind==='stop'||j.kind==='kill'){await c.query("UPDATE servers SET observed_status=$1 WHERE id=$2 AND observed_status<>'deleting'",[b.success?'stopped':'failed',j.server_id]);}
 else if(j.kind==='delete'&&!b.success){await c.query("UPDATE servers SET observed_status='failed' WHERE id=$1",[j.server_id]);}}
 await c.query('COMMIT');return {ok:true};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}});
}
