import type {FastifyInstance} from 'fastify';
import {pool,fail,txt,hash,token,passwordHash,passwordCheck,makeTotp,checkTotp,encrypt,decrypt,audit,admin,scope} from './core.js';
const email=(s:any)=>{const x=txt(s,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x))fail(400,'Invalid email');return x;};
const pass=(s:any)=>{if(typeof s!=='string'||s.length<12||s.length>1024)fail(400,'Password must be 12–1024 characters');return s as string;};
const cookieOptions={path:'/',httpOnly:true,sameSite:'strict' as const,secure:process.env.NODE_ENV==='production',maxAge:7*86400};
async function issue(app:any,reply:any,user:any){const value=token();await pool.query("INSERT INTO sessions(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '7 days')",[user.id,hash(value)]);reply.setCookie('navrylo_session',value,cookieOptions);return {id:user.id,email:user.email,role:user.role};}
export function authRoutes(app:FastifyInstance){
 app.get('/api/auth/status',async()=>({needsSetup:!(await pool.query("SELECT 1 FROM users WHERE role='admin' LIMIT 1")).rowCount}));
 app.get('/api/health',async()=>{await pool.query('SELECT 1');return {ok:true};});
 app.post('/api/auth/bootstrap',async(req,reply)=>{const b=req.body as any;const e=email(b?.email),p=pass(b?.password);const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT pg_advisory_xact_lock(539240193)');if(Number((await client.query("SELECT count(*) AS n FROM users WHERE role='admin'")).rows[0].n))fail(409,'Already initialized');const u=(await client.query("INSERT INTO users(email,password_hash,role) VALUES($1,$2,'admin') RETURNING id,email,role",[e,await passwordHash(p)])).rows[0];await client.query('COMMIT');await audit(u.id,'bootstrap','user',u.id);return issue(app,reply,u);}catch(err){await client.query('ROLLBACK');throw err;}finally{client.release();}});
 app.post('/api/auth/login',async(req,reply)=>{const b=req.body as any;const e=email(b?.email),key=hash(req.ip+':'+e);const bucket=(await pool.query(`INSERT INTO login_attempts(bucket_hash,attempts,expires_at) VALUES($1,0,now()+interval '15 minutes') ON CONFLICT(bucket_hash) DO UPDATE SET attempts=CASE WHEN login_attempts.expires_at<=now() THEN 0 ELSE login_attempts.attempts END,expires_at=CASE WHEN login_attempts.expires_at<=now() THEN now()+interval '15 minutes' ELSE login_attempts.expires_at END RETURNING attempts,expires_at`,[key])).rows[0];if(bucket.attempts>=5)fail(429,'Too many login attempts; try again later');const u=(await pool.query('SELECT * FROM users WHERE email=$1 AND NOT disabled',[e])).rows[0];if(!u||!await passwordCheck(String(b?.password||''),u.password_hash)){await pool.query('UPDATE login_attempts SET attempts=attempts+1 WHERE bucket_hash=$1',[key]);fail(401,'Invalid credentials');}if(u.totp_secret&&b?.stepwise===true){const challenge=token();await pool.query("DELETE FROM auth_challenges WHERE expires_at<now() OR user_id=$1",[u.id]);await pool.query("INSERT INTO auth_challenges(token_hash,user_id,expires_at) VALUES($1,$2,now()+interval '5 minutes')",[hash(challenge),u.id]);return {requires2fa:true,challenge};}if(u.totp_secret&&!checkTotp(decrypt(u.totp_secret),String(b?.totp||''))){await pool.query('UPDATE login_attempts SET attempts=attempts+1 WHERE bucket_hash=$1',[key]);fail(401,'Valid two-factor code required');}await pool.query('DELETE FROM login_attempts WHERE bucket_hash=$1',[key]);await audit(u.id,'login','user',u.id);return issue(app,reply,u);});
 app.post('/api/auth/challenge',async(req,reply)=>{const b=req.body as any,c=await pool.connect();let u:any;let valid=false;try{await c.query('BEGIN');const challenge=(await c.query("SELECT * FROM auth_challenges WHERE token_hash=$1 AND expires_at>now() AND attempts<5 FOR UPDATE",[hash(String(b?.challenge||''))])).rows[0];if(!challenge)fail(401,'Verification expired. Sign in again.');u=(await c.query('SELECT * FROM users WHERE id=$1 AND NOT disabled',[challenge.user_id])).rows[0];valid=!!u?.totp_secret&&checkTotp(decrypt(u.totp_secret),String(b?.code||''));if(valid)await c.query('DELETE FROM auth_challenges WHERE token_hash=$1',[challenge.token_hash]);else await c.query('UPDATE auth_challenges SET attempts=attempts+1 WHERE token_hash=$1',[challenge.token_hash]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}if(!valid)fail(401,'Invalid verification code');await audit(u.id,'login','user',u.id);return issue(app,reply,u);});
 app.post('/api/auth/logout',async(req,reply)=>{const c=(req.cookies as any)?.navrylo_session;if(c)await pool.query('DELETE FROM sessions WHERE token_hash=$1',[hash(c)]);reply.clearCookie('navrylo_session',{path:'/'});return {ok:true};});
 app.get('/api/auth/me',async(req)=>({id:req.actor!.id,email:req.actor!.email,role:req.actor!.role,has2fa:req.actor!.has2fa}));
 app.post('/api/auth/2fa/setup',async(req)=>{if(req.actor?.tokenScopes)fail(403,'Browser session required');const s=makeTotp();await pool.query('UPDATE users SET totp_pending=$1 WHERE id=$2',[encrypt(s),req.actor!.id]);return {secret:s,uri:`otpauth://totp/Fledge:${encodeURIComponent(req.actor!.email)}?secret=${s}&issuer=Fledge`};});
 app.post('/api/auth/2fa/confirm',async(req,reply)=>{if(req.actor?.tokenScopes)fail(403,'Browser session required');const row=(await pool.query('SELECT totp_pending FROM users WHERE id=$1',[req.actor!.id])).rows[0];if(!row?.totp_pending||!checkTotp(decrypt(row.totp_pending),String((req.body as any)?.code||'')))fail(400,'Invalid two-factor code');await pool.query('UPDATE users SET totp_secret=totp_pending,totp_pending=NULL WHERE id=$1',[req.actor!.id]);const old=(req.cookies as any)?.navrylo_session;if(old)await pool.query('DELETE FROM sessions WHERE token_hash=$1',[hash(old)]);await audit(req.actor!.id,'2fa.enable','user',req.actor!.id);await issue(app,reply,req.actor);return {ok:true};});
 app.get('/api/tokens',async(req)=>{admin(req);return (await pool.query('SELECT id,name,scopes,expires_at,created_at FROM api_tokens WHERE user_id=$1 ORDER BY created_at DESC',[req.actor!.id])).rows;});
 app.post('/api/tokens',async(req)=>{admin(req);if(req.actor?.tokenScopes)fail(403,'Browser session required');const b=req.body as any,scopes=b?.scopes;if(!Array.isArray(scopes)||!scopes.length||scopes.some((v:any)=>!['provision','read','suspend'].includes(v)))fail(400,'Allowed scopes: provision, read, suspend');const t=token();const r=(await pool.query('INSERT INTO api_tokens(user_id,name,token_hash,scopes,expires_at) VALUES($1,$2,$3,$4,$5) RETURNING id,name,scopes,expires_at',[req.actor!.id,txt(b?.name),hash(t),scopes,b?.expiresAt||null])).rows[0];await audit(req.actor!.id,'token.create','token',r.id);return {...r,token:t};});
 app.delete('/api/tokens/:id',async(req)=>{admin(req);const id=(req.params as any).id;const r=await pool.query('DELETE FROM api_tokens WHERE id=$1 AND user_id=$2 RETURNING id',[id,req.actor!.id]);if(!r.rowCount)fail(404,'Token not found');await audit(req.actor!.id,'token.delete','token',id);return {ok:true};});
}
