import type {FastifyInstance} from 'fastify';
import {pool,admin,scope,fail,txt,positive,asId,page,nodeShape,audit,token,hash,passwordHash} from './core.js';
import {usageOf} from './quota.js';
import {sendTemplate} from './email.js';
import {validateLimitSet,toStorage} from './rookery-settings.js';
const host=(v:any)=>{const t=txt(v,253);if(!/^[A-Za-z0-9.:\[\]-]+$/.test(t))fail(400,'Enter a hostname or IP address');return t;};
const selectNodes=`SELECT n.*,coalesce(sum(s.memory_mb),0) AS reserved_memory,coalesce(sum(s.cpu_percent),0) AS reserved_cpu,coalesce(sum(s.disk_mb),0) AS reserved_disk FROM nodes n LEFT JOIN servers s ON s.node_id=n.id AND s.deleted_at IS NULL WHERE n.deleted_at IS NULL GROUP BY n.id`;
const customerShape=(u:any)=>({id:u.id,email:u.email,role:u.role,disabled:u.disabled,status:u.status||'active',signupSource:u.signup_source||'admin',emailVerifiedAt:u.email_verified_at||null,createdAt:u.created_at,serverCount:Number(u.server_count||0),quota:u.quota||{},...(u.used_memory!==undefined?{usage:{servers:Number(u.server_count||0),memoryMb:Number(u.used_memory),cpuPercent:Number(u.used_cpu),diskMb:Number(u.used_disk)}}:{})});
export function providerRoutes(app:FastifyInstance){
 app.get('/api/overview',async(req)=>{admin(req);scope(req,'read');const [nodes,servers,customers,failed,capacity]=await Promise.all([
 pool.query("SELECT status,count(*)::int AS count FROM nodes WHERE deleted_at IS NULL GROUP BY status"),pool.query("SELECT CASE WHEN n.status='disconnected' THEN 'unreachable' ELSE s.observed_status END AS status,count(*)::int AS count FROM servers s JOIN nodes n ON n.id=s.node_id WHERE s.deleted_at IS NULL GROUP BY 1"),pool.query("SELECT count(*)::int AS count FROM users WHERE role='customer'"),pool.query("SELECT count(*)::int AS count FROM jobs WHERE state='failed'"),pool.query(selectNodes)]);
 return {nodes:Object.fromEntries(nodes.rows.map(x=>[x.status,x.count])),servers:Object.fromEntries(servers.rows.map(x=>[x.status,x.count])),customers:customers.rows[0].count,failedJobs:failed.rows[0].count,capacity:capacity.rows.map(nodeShape)};});
 app.get('/api/nodes',async(req)=>{admin(req);scope(req,'read');return (await pool.query(selectNodes+' ORDER BY n.created_at DESC')).rows.map(nodeShape);});
 app.get('/api/nodes/:id',async(req)=>{admin(req);scope(req,'read');const r=await pool.query(`SELECT * FROM (${selectNodes}) x WHERE id=$1`,[asId((req.params as any).id)]);if(!r.rowCount)fail(404,'Node not found');return nodeShape(r.rows[0]);});
 app.post('/api/nodes',async(req)=>{admin(req);scope(req,'provision');const b=req.body as any;const row=(await pool.query('INSERT INTO nodes(name,location,memory_mb,cpu_percent,disk_mb,headroom_mb) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[txt(b?.name),txt(b?.location),positive(b?.memoryMb),positive(b?.cpuPercent),positive(b?.diskMb),positive(b?.headroomMb??512,0)])).rows[0];await audit(req.actor!.id,'node.create','node',row.id);return nodeShape(row);});
 app.post('/api/nodes/:id/enrollment',async(req)=>{admin(req);scope(req,'provision');const id=asId((req.params as any).id),secret=token();const r=await pool.query("UPDATE nodes SET enrollment_hash=$1,enrollment_expires_at=now()+interval '10 minutes',credential_hash=NULL,status='disconnected' WHERE id=$2 AND deleted_at IS NULL RETURNING id",[hash(secret),id]);if(!r.rowCount)fail(404,'Node not found');await audit(req.actor!.id,'node.enrollment.rotate','node',id);return {nodeId:id,token:secret,expiresInSeconds:600};});
 app.patch('/api/nodes/:id',async(req)=>{admin(req);scope(req,'provision');const id=asId((req.params as any).id),b=req.body as any;const r=await pool.query('UPDATE nodes SET name=COALESCE($1,name),location=COALESCE($2,location),draining=COALESCE($3,draining),headroom_mb=COALESCE($4,headroom_mb),public_host=CASE WHEN $6::boolean THEN $7 ELSE public_host END WHERE id=$5 AND deleted_at IS NULL RETURNING *',[b?.name===undefined?null:txt(b.name),b?.location===undefined?null:txt(b.location),b?.draining===undefined?null:Boolean(b.draining),b?.headroomMb===undefined?null:positive(b.headroomMb,0),id,b?.publicHost!==undefined,b?.publicHost?host(b.publicHost):null]);if(!r.rowCount)fail(404,'Node not found');await audit(req.actor!.id,'node.update','node',id);return nodeShape(r.rows[0]);});
 app.delete('/api/nodes/:id',async(req)=>{admin(req);scope(req,'provision');const id=asId((req.params as any).id),c=await pool.connect();try{await c.query('BEGIN');const n=await c.query('SELECT id FROM nodes WHERE id=$1 AND deleted_at IS NULL FOR UPDATE',[id]);if(!n.rowCount)fail(404,'Node not found');const count=await c.query('SELECT count(*)::int AS n FROM servers WHERE node_id=$1 AND deleted_at IS NULL',[id]);if(count.rows[0].n)fail(409,'Node still has servers; drain and remove them first');await c.query("UPDATE nodes SET deleted_at=now(),status='disconnected',credential_hash=NULL,enrollment_hash=NULL WHERE id=$1",[id]);await c.query('COMMIT');}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}await audit(req.actor!.id,'node.delete','node',id);return {ok:true};});
 app.get('/api/customers',async(req)=>{admin(req);scope(req,'read');const {limit,offset}=page(req.query);return (await pool.query("SELECT u.*,count(s.id)::int AS server_count,coalesce(sum(s.memory_mb),0)::int AS used_memory,coalesce(sum(s.cpu_percent),0)::int AS used_cpu,coalesce(sum(s.disk_mb),0)::int AS used_disk FROM users u LEFT JOIN servers s ON s.owner_id=u.id AND s.deleted_at IS NULL WHERE u.role='customer' GROUP BY u.id ORDER BY u.created_at DESC LIMIT $1 OFFSET $2",[limit,offset])).rows.map(customerShape);});
 app.get('/api/customers/:id',async(req)=>{admin(req);scope(req,'read');const r=await pool.query('SELECT * FROM users WHERE id=$1 AND role=$2',[asId((req.params as any).id),'customer']);if(!r.rowCount)fail(404,'Customer not found');return {...customerShape(r.rows[0]),usage:await usageOf(r.rows[0].id)};});
 app.post('/api/customers',async(req)=>{admin(req);scope(req,'provision');const b=req.body as any,e=txt(b?.email,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))fail(400,'Invalid email');const password=b?.password||token();if(typeof password!=='string'||password.length<12)fail(400,'Password must be at least 12 characters');const r=(await pool.query("INSERT INTO users(email,password_hash,role) VALUES($1,$2,'customer') RETURNING *",[e,await passwordHash(password)])).rows[0];await audit(req.actor!.id,'customer.create','user',r.id);return {...customerShape(r),temporaryPassword:b?.password?undefined:password};});
 app.patch('/api/customers/:id',async(req)=>{admin(req);scope(req,'provision');const id=asId((req.params as any).id),b=req.body as any;if(b?.password!==undefined&&(typeof b.password!=='string'||b.password.length<12))fail(400,'Password too short');const quota=b?.quota===undefined?null:JSON.stringify(toStorage(validateLimitSet(b.quota,'quota')));const r=await pool.query("UPDATE users SET disabled=COALESCE($1,disabled),password_hash=COALESCE($2,password_hash),quota=COALESCE($4::jsonb,quota) WHERE id=$3 AND role='customer' RETURNING *",[b?.disabled===undefined?null:Boolean(b.disabled),b?.password?await passwordHash(b.password):null,id,quota]);if(!r.rowCount)fail(404,'Customer not found');if(b?.password||b?.disabled===true)await pool.query('DELETE FROM sessions WHERE user_id=$1',[id]);if(b?.password)void sendTemplate('password_changed',r.rows[0].email,{when:new Date().toUTCString()},{userId:id}).catch(()=>{});await audit(req.actor!.id,'customer.update','user',id,{quota:b?.quota!==undefined});return customerShape(r.rows[0]);});
 app.get('/api/jobs',async(req)=>{scope(req,'read');const p=page(req.query),id=(req.query as any)?.serverId;let where='';const args:any[]=[];if(req.actor?.role!=='admin'){where="WHERE (s.owner_id=$1 OR EXISTS(SELECT 1 FROM collaborators c WHERE c.server_id=s.id AND c.user_id=$1 AND c.permissions && ARRAY['view','console','files','backups','manage']::text[]))";args.push(req.actor!.id);}if(id){asId(id);where+=where?' AND ':'WHERE ';where+=`j.server_id=$${args.length+1}`;args.push(id);}args.push(p.limit,p.offset);return (await pool.query(`SELECT DISTINCT j.id,j.server_id AS "serverId",j.node_id AS "nodeId",j.kind,j.state,j.error,j.created_at AS "createdAt",j.started_at AS "startedAt",j.finished_at AS "finishedAt" FROM jobs j LEFT JOIN servers s ON s.id=j.server_id ${where} ORDER BY j.created_at DESC LIMIT $${args.length-1} OFFSET $${args.length}`,args)).rows;});
}
