import type {FastifyInstance,FastifyRequest} from 'fastify';
import {randomBytes} from 'node:crypto';
import {pool,admin,scope,fail,txt,positive,asId,page,serverAccess,serverShape,effectivePermissions,enqueue,audit,imageAllowed} from './core.js';
import {getObjectStream,backupEnabled} from './storage.js';
import {deleteBackup} from './backup-maintenance.js';
const detailed=`SELECT s.*,n.name AS node_name,n.location,n.status AS node_status,t.image,t.startup,t.internal_ports,t.env FROM servers s JOIN nodes n ON n.id=s.node_id JOIN templates t ON t.id=s.template_id`;
const validAction=new Set(['start','stop','restart','kill','suspend','unsuspend','reinstall','backup','restore']);
function active(s:any){if(s.observed_status==='deleting')fail(409,'Server deletion is pending');return s;}
async function createBackup(req:FastifyRequest,s:any){active(s);if(!backupEnabled())fail(503,'Backup storage is not configured');const c=await pool.connect();try{await c.query('BEGIN');const b=(await c.query('INSERT INTO backups(server_id,object_key) VALUES($1,$2) RETURNING *',[s.id,`servers/${s.id}/backups/${crypto.randomUUID()}.tar.gz`])).rows[0];const j=(await c.query("INSERT INTO jobs(node_id,server_id,kind,payload) VALUES($1,$2,'backup',$3) RETURNING *",[s.node_id,s.id,JSON.stringify({backupId:b.id})])).rows[0];await c.query('UPDATE backups SET job_id=$1 WHERE id=$2',[j.id,b.id]);await c.query('COMMIT');await audit(req.actor!.id,'backup.create','server',s.id,{backupId:b.id});return {id:b.id,jobId:j.id,state:'queued'};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
async function waitJob(id:string,ms=26000){const deadline=Date.now()+ms;while(Date.now()<deadline){const j=(await pool.query('SELECT state,result,error FROM jobs WHERE id=$1',[id])).rows[0];if(j.state==='succeeded')return j.result;if(j.state==='failed')fail(502,j.error||'Agent operation failed');await new Promise(r=>setTimeout(r,350));}fail(504,'Agent did not respond in time; job may still complete');}
async function syncOperation(s:any,kind:string,payload:any={}){active(s);if(s.node_status!=='connected')fail(503,'Node is disconnected');const j=await enqueue(s.node_id,s.id,kind,payload);return waitJob(j.id);}
const path=(v:any)=>{if(typeof v!=='string'||!v.startsWith('/')||v.length>2048||v.includes('\0'))fail(400,'Absolute virtual path required');return v as string;};
async function requireManage(req:FastifyRequest,id:string){const s=active(await serverAccess(req,id,'manage'));if(req.actor?.role!=='admin'&&s.owner_id!==req.actor?.id&&!(s.permissions||[]).includes('manage'))fail(403,'Manage permission required');return s;}
export function serverRoutes(app:FastifyInstance){
 app.get('/api/servers',async(req)=>{scope(req,'read');const p=page(req.query),args:any[]=[];let where='s.deleted_at IS NULL';if(req.actor!.role!=='admin'){args.push(req.actor!.id);where+=" AND (s.owner_id=$1 OR EXISTS(SELECT 1 FROM collaborators c WHERE c.server_id=s.id AND c.user_id=$1 AND c.permissions && ARRAY['view','console','files','backups','manage']::text[]))";}args.push(p.limit,p.offset);return (await pool.query(`${detailed} WHERE ${where} ORDER BY s.created_at DESC LIMIT $${args.length-1} OFFSET $${args.length}`,args)).rows.map(serverShape);});
 app.get('/api/servers/:id',async(req)=>{scope(req,'read');const s=await serverAccess(req,(req.params as any).id);return {...serverShape(s),effectivePermissions:effectivePermissions(req,s),...(!req.actor!.tokenScopes&&(req.actor!.role==='admin'||req.actor!.id===s.owner_id||s.permissions?.includes('manage'))?{variables:s.variables}:{})};});
 app.post('/api/servers',async(req)=>{admin(req);scope(req,'provision');const b=req.body as any;const ownerId=asId(b?.ownerId),templateId=txt(b?.templateId),name=txt(b?.name),location=b?.location?txt(b.location):null;
 const t=(await pool.query('SELECT * FROM templates WHERE id=$1',[templateId])).rows[0];if(!t)fail(404,'Template not found');if(!imageAllowed(t.image))fail(403,'Template image is not currently allowlisted');const memory=positive(b.memoryMb??t.memory_mb),cpu=positive(b.cpuPercent??t.cpu_percent),disk=positive(b.diskMb??t.disk_mb);const owner=(await pool.query("SELECT id FROM users WHERE id=$1 AND role='customer' AND NOT disabled",[ownerId])).rows[0];if(!owner)fail(404,'Active customer not found');
 const ports=t.internal_ports as Array<{offset:number,protocol:string,container:number}>;const c=await pool.connect();try{await c.query('BEGIN');const nodes=(await c.query('SELECT * FROM nodes WHERE ($1::uuid IS NULL OR id=$1) AND ($2::text IS NULL OR location=$2) AND status=$3 AND NOT draining AND deleted_at IS NULL ORDER BY (memory_mb-headroom_mb) DESC,id FOR UPDATE',[b.nodeId?asId(b.nodeId):null,location,'connected'])).rows;let chosen:any,port=0;const rejection:any[]=[];
 for(const n of nodes){const used=(await c.query('SELECT coalesce(sum(memory_mb),0) AS mem,coalesce(sum(cpu_percent),0) AS cpu,coalesce(sum(disk_mb),0) AS disk FROM servers WHERE node_id=$1 AND deleted_at IS NULL',[n.id])).rows[0];if(Number(used.mem)+memory>n.memory_mb-n.headroom_mb||Number(used.cpu)+cpu>n.cpu_percent||Number(used.disk)+disk>n.disk_mb){rejection.push({nodeId:n.id,reason:'insufficient reserved capacity'});continue;}if(Number.isFinite(Number(n.usage?.diskFreeMb))&&Number(n.usage.diskFreeMb)<disk+n.headroom_mb){rejection.push({nodeId:n.id,reason:'insufficient actual free disk'});continue;}
 const occupied=new Set((await c.query('SELECT port,protocol FROM allocations WHERE node_id=$1',[n.id])).rows.map((x:any)=>`${x.port}/${x.protocol}`));const start=b.port===undefined?20000:positive(b.port,1024,65535),end=b.port===undefined?50000:start;for(let p=start;p<=end;p++){if(ports.every(x=>p+x.offset<=65535&&!occupied.has(`${p+x.offset}/${x.protocol}`))){chosen=n;port=p;break;}}if(chosen)break;rejection.push({nodeId:n.id,reason:'no compatible free ports'});}
 if(!chosen)fail(409,`No eligible node: ${JSON.stringify(rejection.length?rejection:[{reason:'no connected node in selected location/pool'}])}`);
 const variables=templateId==='valheim'?{SERVER_PASS:randomBytes(18).toString('base64url')}:t.image.startsWith('itzg/minecraft-server:')?{RCON_PASSWORD:randomBytes(24).toString('base64url')}:{};const server=(await c.query('INSERT INTO servers(name,owner_id,node_id,template_id,memory_mb,cpu_percent,disk_mb,port,observed_status,variables) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[name,ownerId,chosen.id,templateId,memory,cpu,disk,port,'provisioning',JSON.stringify(variables)])).rows[0];for(const x of ports)await c.query('INSERT INTO allocations(node_id,server_id,port,protocol) VALUES($1,$2,$3,$4)',[chosen.id,server.id,port+x.offset,x.protocol]);const job=(await c.query("INSERT INTO jobs(node_id,server_id,kind) VALUES($1,$2,'create') RETURNING id,state",[chosen.id,server.id])).rows[0];await c.query('COMMIT');await audit(req.actor!.id,'server.create','server',server.id,{nodeId:chosen.id,placement:'selected by capacity and port availability',rejected:rejection});return {...serverShape({...server,node_name:chosen.name,location:chosen.location,node_status:chosen.status}),job,placement:{selected:chosen.id,rejected:rejection}};
 }catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}});
 app.patch('/api/servers/:id',async(req)=>{admin(req);scope(req,'provision');const id=asId((req.params as any).id),b=req.body as any;const c=await pool.connect();try{await c.query('BEGIN');const s=(await c.query('SELECT * FROM servers WHERE id=$1 AND deleted_at IS NULL FOR UPDATE',[id])).rows[0];if(!s)fail(404,'Server not found');active(s);if(b?.nodeId!==undefined||b?.port!==undefined||b?.ownerId!==undefined||b?.templateId!==undefined)fail(400,'Moving nodes/ports, changing owner or template is unsupported; create a new server and restore a backup');
 const n=(await c.query('SELECT * FROM nodes WHERE id=$1 FOR UPDATE',[s.node_id])).rows[0];const memory=b?.memoryMb===undefined?s.memory_mb:positive(b.memoryMb),cpu=b?.cpuPercent===undefined?s.cpu_percent:positive(b.cpuPercent),disk=b?.diskMb===undefined?s.disk_mb:positive(b.diskMb);const used=(await c.query('SELECT coalesce(sum(memory_mb),0) mem,coalesce(sum(cpu_percent),0) cpu,coalesce(sum(disk_mb),0) disk FROM servers WHERE node_id=$1 AND deleted_at IS NULL AND id<>$2',[n.id,id])).rows[0];if(Number(used.mem)+memory>n.memory_mb-n.headroom_mb||Number(used.cpu)+cpu>n.cpu_percent||Number(used.disk)+disk>n.disk_mb)fail(409,'Insufficient reserved capacity');
 const variables=b?.variables===undefined?s.variables:b.variables;if(typeof variables!=='object'||Array.isArray(variables)||Object.entries(variables).some(([k,v])=>!/^[A-Z_][A-Z0-9_]*$/.test(k)||typeof v!=='string'))fail(400,'Invalid variables');const u=(await c.query('UPDATE servers SET name=$1,memory_mb=$2,cpu_percent=$3,disk_mb=$4,variables=$5,updated_at=now() WHERE id=$6 RETURNING *',[b?.name===undefined?s.name:txt(b.name),memory,cpu,disk,JSON.stringify(variables),id])).rows[0];let job=null;if(memory!==s.memory_mb||cpu!==s.cpu_percent||JSON.stringify(variables)!==JSON.stringify(s.variables)){job=(await c.query("INSERT INTO jobs(node_id,server_id,kind,payload) VALUES($1,$2,'configure',$3) RETURNING id,state",[n.id,id,JSON.stringify({recreate:JSON.stringify(variables)!==JSON.stringify(s.variables)})])).rows[0];}await c.query('COMMIT');await audit(req.actor!.id,'server.update','server',id);return {...serverShape({...u,node_name:n.name,location:n.location,node_status:n.status}),job};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}});
 app.patch('/api/servers/:id/settings',async(req)=>{const s=await requireManage(req,(req.params as any).id),b=req.body as any,vars=b?.variables;if(!vars||typeof vars!=='object'||Array.isArray(vars)||!Object.keys(vars).length||Object.entries(vars).some(([k,v])=>!s.editable_variables.includes(k)||typeof v!=='string'||v.length>4096)||('SERVER_PASS' in vars&&String(vars.SERVER_PASS).length<5))fail(400,'Only declared editable template variables may be changed (strings up to 4096 characters)');const c=await pool.connect();try{await c.query('BEGIN');await c.query('UPDATE servers SET variables=variables||$1::jsonb,updated_at=now() WHERE id=$2',[JSON.stringify(vars),s.id]);const j=(await c.query("INSERT INTO jobs(node_id,server_id,kind,payload) VALUES($1,$2,'configure',$3) RETURNING id,state",[s.node_id,s.id,JSON.stringify({recreate:true})])).rows[0];await c.query('COMMIT');await audit(req.actor!.id,'server.settings.update','server',s.id,{keys:Object.keys(vars)});return {jobId:j.id,state:j.state};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}});
 app.delete('/api/servers/:id',async(req)=>{admin(req);scope(req,'provision');if((req.body as any)?.confirm!==true&&(req.query as any)?.confirm!=='true')fail(400,'Deletion permanently removes local data; send {confirm:true} or ?confirm=true');const s=await serverAccess(req,(req.params as any).id);if(s.node_status!=='connected')fail(503,'Cannot delete this server while its node is disconnected. Reconnect the node, then retry deletion.');const c=await pool.connect();try{await c.query('BEGIN');const row=(await c.query('SELECT observed_status FROM servers WHERE id=$1 AND deleted_at IS NULL FOR UPDATE',[s.id])).rows[0];if(!row)fail(404,'Server not found');if(row.observed_status==='deleting')fail(409,'Deletion is already pending; check Recent jobs for its result.');const j=(await c.query("INSERT INTO jobs(node_id,server_id,kind) VALUES($1,$2,'delete') RETURNING id,state",[s.node_id,s.id])).rows[0];await c.query("UPDATE servers SET observed_status='deleting' WHERE id=$1",[s.id]);await c.query('COMMIT');await audit(req.actor!.id,'server.delete.request','server',s.id,{jobId:j.id});return {jobId:j.id,state:j.state};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}});
 app.post('/api/servers/:id/actions',async(req)=>{const s=active(await serverAccess(req,(req.params as any).id,'manage')),b=req.body as any,action=b?.action;if(!validAction.has(action))fail(400,'Unknown action');if(req.actor?.tokenScopes){if(action!=='suspend'&&action!=='unsuspend')fail(403,'API tokens can only suspend or unsuspend servers');scope(req,'suspend');}if(['suspend','unsuspend','reinstall'].includes(action))admin(req);if(s.suspended&&!['unsuspend','backup','restore'].includes(action))fail(409,'Server is suspended');if(action==='backup')return createBackup(req,s);if(action==='restore'){if(b?.confirm!==true)fail(400,'Restore overwrites target files; confirm:true required');if(!backupEnabled())fail(503,'Backup storage not configured');const c=await pool.connect();try{await c.query('BEGIN');const r=(await c.query("SELECT b.* FROM backups b JOIN servers source ON source.id=b.server_id WHERE b.id=$1 AND b.state='succeeded' AND ($2::boolean OR (source.owner_id=$3 AND (source.owner_id=$4 OR EXISTS (SELECT 1 FROM collaborators bc WHERE bc.server_id=source.id AND bc.user_id=$4 AND bc.permissions && ARRAY['backups','manage']::text[])))) FOR UPDATE OF b",[asId(b?.backupId),req.actor!.role==='admin',s.owner_id,req.actor!.id])).rows[0];if(!r)fail(404,'Usable backup not found');const j=(await c.query("INSERT INTO jobs(node_id,server_id,kind,payload) VALUES($1,$2,'restore',$3) RETURNING id,state",[s.node_id,s.id,JSON.stringify({backupId:r.id})])).rows[0];await c.query('COMMIT');await audit(req.actor!.id,'restore.request','server',s.id,{backupId:r.id});return {jobId:j.id,state:j.state};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 if(action==='reinstall'&&b?.confirm!==true)fail(400,'Reinstall deletes data; confirm:true required');const kind=action==='suspend'?'stop':action==='unsuspend'?'start':action;const j=await enqueue(s.node_id,s.id,kind);await pool.query('UPDATE servers SET desired_status=$1,suspended=$2 WHERE id=$3',[['stop','kill','suspend'].includes(action)?'stopped':'running',action==='suspend'?true:action==='unsuspend'?false:s.suspended,s.id]);await audit(req.actor!.id,`server.${action}`,'server',s.id);return {jobId:j.id,state:j.state};});
 app.get('/api/servers/:id/console',async(req)=>{scope(req,'read');const s=await serverAccess(req,(req.params as any).id,'console');return syncOperation(s,'logs');});
 app.post('/api/servers/:id/console',async(req)=>{const s=await serverAccess(req,(req.params as any).id,'console');return syncOperation(s,'command',{command:txt((req.body as any)?.command,1024)});});
 app.get('/api/servers/:id/files',async(req)=>{scope(req,'read');const s=await serverAccess(req,(req.params as any).id,'files');return syncOperation(s,'file.list',{path:path((req.query as any)?.path||'/')});});
 app.get('/api/servers/:id/files/content',async(req)=>{scope(req,'read');const s=await serverAccess(req,(req.params as any).id,'files');return syncOperation(s,'file.read',{path:path((req.query as any)?.path)});});
 app.put('/api/servers/:id/files/content',async(req)=>{const s=await serverAccess(req,(req.params as any).id,'files');const b=req.body as any;if(typeof b?.content!=='string'||Buffer.byteLength(b.content)>1024*1024)fail(413,'Editor limit: 1 MiB');return syncOperation(s,'file.write',{path:path((req.query as any)?.path),content:b.content});});
 app.post('/api/servers/:id/files/mkdir',async(req)=>{const s=await serverAccess(req,(req.params as any).id,'files');return syncOperation(s,'file.mkdir',{path:path((req.body as any)?.path)});});
 app.post('/api/servers/:id/files/extract',async(req)=>{const s=await serverAccess(req,(req.params as any).id,'files');return syncOperation(s,'file.extract',{path:path((req.body as any)?.path)});});
 app.post('/api/servers/:id/files/upload',async(req)=>{const s=await serverAccess(req,(req.params as any).id,'files');const part=await req.file({limits:{fileSize:8*1024*1024,files:1}});if(!part)fail(400,'Missing file');const data=await part!.toBuffer();const dir=String((part!.fields?.path as any)?.value||'/');return syncOperation(s,'file.upload',{path:path(dir+'/'+part!.filename),data:data.toString('base64')});});
 app.get('/api/servers/:id/files/download',async(req,reply)=>{scope(req,'read');const s=await serverAccess(req,(req.params as any).id,'files');const result=await syncOperation(s,'file.download',{path:path((req.query as any)?.path)});const bytes=Buffer.from(result.data,'base64');reply.header('content-type','application/octet-stream').header('content-disposition',`attachment; filename="${String(result.name||'download').replace(/["\r\n]/g,'_')}"`);return reply.send(bytes);});
 app.get('/api/servers/:id/backups',async(req)=>{scope(req,'read');const s=await serverAccess(req,(req.params as any).id,'backups');return (await pool.query('SELECT id,state,size_bytes AS "sizeBytes",error,created_at AS "createdAt",completed_at AS "completedAt" FROM backups WHERE server_id=$1 ORDER BY created_at DESC',[s.id])).rows;});
 app.get('/api/servers/:id/backups/policy',async(req)=>{scope(req,'read');const s=await serverAccess(req,(req.params as any).id,'backups');return {retentionDays:s.backup_retention_days};});
 app.patch('/api/servers/:id/backups/policy',async(req)=>{const s=await requireManage(req,(req.params as any).id);const days=positive((req.body as any)?.retentionDays,0,3650);await pool.query('UPDATE servers SET backup_retention_days=$1,updated_at=now() WHERE id=$2',[days,s.id]);await audit(req.actor!.id,'backup.retention.update','server',s.id,{retentionDays:days});return {retentionDays:days};});
 app.post('/api/servers/:id/backups',async(req)=>createBackup(req,await serverAccess(req,(req.params as any).id,'backups')));
 app.delete('/api/servers/:id/backups/:backupId',async(req)=>{const s=await serverAccess(req,(req.params as any).id,'backups');const id=asId((req.params as any).backupId),b=(await pool.query('SELECT id FROM backups WHERE id=$1 AND server_id=$2',[id,s.id])).rows[0];if(!b)fail(404,'Backup not found');if(!backupEnabled())fail(503,'Backup storage is not configured');if(!await deleteBackup(id))fail(404,'Backup not found');await audit(req.actor!.id,'backup.delete','backup',id);return {ok:true};});
 app.get('/api/servers/:id/backups/:backupId/download',async(req,reply)=>{scope(req,'read');const s=await serverAccess(req,(req.params as any).id,'backups');const b=(await pool.query("SELECT object_key FROM backups WHERE id=$1 AND server_id=$2 AND state='succeeded'",[asId((req.params as any).backupId),s.id])).rows[0];if(!b)fail(404,'Backup not found');const object=await getObjectStream(b.object_key);reply.header('content-type','application/octet-stream');if(object.contentLength!==undefined)reply.header('content-length',object.contentLength);reply.header('content-disposition',`attachment; filename="${String((req.params as any).backupId).replace(/["\r\n]/g,'_')}.tar.gz"`);return reply.send(object.body);});
 app.get('/api/servers/:id/schedules',async(req)=>{scope(req,'read');const s=await serverAccess(req,(req.params as any).id,'manage');return (await pool.query('SELECT * FROM schedules WHERE server_id=$1 ORDER BY created_at',[s.id])).rows;});
 app.post('/api/servers/:id/schedules',async(req)=>{const s=await requireManage(req,(req.params as any).id),b=req.body as any;if(!['command','backup'].includes(b?.kind))fail(400,'Invalid schedule kind');if(b.kind==='command'&&!s.image.startsWith('itzg/minecraft-server:'))fail(409,'Scheduled commands are only supported for Minecraft Java');if(b.kind==='backup'&&!backupEnabled())fail(503,'Backup storage not configured');const r=(await pool.query("INSERT INTO schedules(server_id,kind,command,interval_minutes,next_run_at) VALUES($1,$2,$3,$4,now()+($4::text||' minutes')::interval) RETURNING *",[s.id,b.kind,b.kind==='command'?txt(b.command,1024):null,positive(b.intervalMinutes,5,10080)])).rows[0];return r;});
 app.delete('/api/servers/:id/schedules/:scheduleId',async(req)=>{const s=await requireManage(req,(req.params as any).id);const r=await pool.query('DELETE FROM schedules WHERE id=$1 AND server_id=$2 RETURNING id',[asId((req.params as any).scheduleId),s.id]);if(!r.rowCount)fail(404,'Schedule not found');return {ok:true};});
 app.get('/api/servers/:id/collaborators',async(req)=>{const s=await requireManage(req,(req.params as any).id);return (await pool.query('SELECT c.user_id AS "userId",u.email,c.permissions FROM collaborators c JOIN users u ON u.id=c.user_id WHERE c.server_id=$1',[s.id])).rows;});
 app.post('/api/servers/:id/collaborators',async(req)=>{const s=await requireManage(req,(req.params as any).id),b=req.body as any,perms=b?.permissions;if(!Array.isArray(perms)||perms.some((x:any)=>!['view','console','files','backups','manage'].includes(x)))fail(400,'Invalid permissions');const u=(await pool.query("SELECT id FROM users WHERE email=$1 AND role='customer' AND NOT disabled",[txt(b?.email,254).toLowerCase()])).rows[0];if(!u||u.id===s.owner_id)fail(404,'Other customer account not found');await pool.query('INSERT INTO collaborators(server_id,user_id,permissions) VALUES($1,$2,$3) ON CONFLICT(server_id,user_id) DO UPDATE SET permissions=$3',[s.id,u.id,perms]);await audit(req.actor!.id,'collaborator.upsert','server',s.id,{userId:u.id});return {userId:u.id,permissions:perms};});
 app.delete('/api/servers/:id/collaborators/:userId',async(req)=>{const s=await requireManage(req,(req.params as any).id),id=asId((req.params as any).userId);await pool.query('DELETE FROM collaborators WHERE server_id=$1 AND user_id=$2',[s.id,id]);await audit(req.actor!.id,'collaborator.delete','server',s.id,{userId:id});return {ok:true};});
}
