// Run against a disposable empty database/API, never production. Exercises HTTP + PostgreSQL + agent protocol, not Docker.
import {randomBytes} from 'node:crypto';
import {authenticator} from 'otplib';
import pg from 'pg';
import {liveTests} from './live.mjs';
const base=process.env.TEST_API_URL||'http://127.0.0.1:4172';
let cookie='';let count=0;
async function call(method,path,body,headers={}){const response=await fetch(base+path,{method,headers:{...(body?{'content-type':'application/json'}:{}),...(cookie?{cookie}:{}),...headers},body:body?JSON.stringify(body):undefined});const setCookie=response.headers.get('set-cookie');if(setCookie)cookie=setCookie.split(';')[0];const text=await response.text();let data;try{data=JSON.parse(text)}catch{data=text}return {code:response.status,data};}
function ok(r,label){if(r.code<200||r.code>=300)throw Error(`${label}: ${r.code} ${JSON.stringify(r.data)}`);count++;return r.data;}
function status(r,code,label){if(r.code!==code)throw Error(`${label}: expected ${code}, got ${r.code}: ${JSON.stringify(r.data)}`);count++;}
status(await call('GET','/api/updates'),401,'updates require authentication');
const password=randomBytes(20).toString('base64url'),adminEmail='smoke-'+randomBytes(4).toString('hex')+'@example.test';
const a=ok(await call('POST','/api/auth/bootstrap',{email:adminEmail,password}),'bootstrap');status(await call('GET','/api/nodes'),403,'admin 2fa required');
const setup=ok(await call('POST','/api/auth/2fa/setup',{}),'2fa setup');const pre2faCookie=cookie;ok(await call('POST','/api/auth/2fa/confirm',{code:authenticator.generate(setup.secret)}),'2fa confirm');if(cookie===pre2faCookie)throw Error('2FA activation did not rotate the session');count++;status(await call('GET','/api/auth/me',undefined,{cookie:pre2faCookie}),401,'pre-2FA session revoked');ok(await call('POST','/api/auth/logout',{}),'logout');status(await call('POST','/api/auth/login',{email:adminEmail,password}),401,'2fa enforced');ok(await call('POST','/api/auth/login',{email:adminEmail,password,totp:authenticator.generate(setup.secret)}),'2fa login');
const updateInfo=ok(await call('GET','/api/updates'),'admin release check');if(updateInfo.currentVersion!=='0.1.0'||updateInfo.repository!=='kavaliersdelikt/navrylo'||!updateInfo.releaseUrl.startsWith('https://github.com/kavaliersdelikt/navrylo/releases/'))throw Error('release check returned invalid project metadata');count++;
const throttleEmail='throttle-'+randomBytes(4).toString('hex')+'@example.test';for(let i=0;i<5;i++)status(await call('POST','/api/auth/login',{email:throttleEmail,password}),401,'invalid login attempt');status(await call('POST','/api/auth/login',{email:throttleEmail,password}),429,'login throttled after five failures');
const customer=ok(await call('POST','/api/customers',{email:'customer-'+randomBytes(4).toString('hex')+'@example.test'}),'customer');const other=ok(await call('POST','/api/customers',{email:'other-'+randomBytes(4).toString('hex')+'@example.test'}),'other customer');
async function node(name){const n=ok(await call('POST','/api/nodes',{name,location:'smoke',memoryMb:2048,cpuPercent:400,diskMb:30000,headroomMb:256}),'node create');const t=ok(await call('POST',`/api/nodes/${n.id}/enrollment`,{}),'enrollment');const enrolled=ok(await call('POST','/api/agent/enroll',{nodeId:n.id,token:t.token}),'agent enroll');const headers={'x-node-id':n.id,authorization:'Bearer '+enrolled.credential};ok(await call('POST','/api/agent/heartbeat',{version:'test',usage:{diskFreeMb:10000},servers:[]},headers),'heartbeat');return {id:n.id,headers};}
const n1=await node('alpha'),n2=await node('beta');
const server=ok(await call('POST','/api/servers',{name:'Minecraft',ownerId:customer.id,templateId:'minecraft-java',location:'smoke',nodeId:n1.id,memoryMb:512,cpuPercent:100,diskMb:2048,port:25565}),'server create');
status(await call('POST','/api/servers',{name:'Conflict',ownerId:customer.id,templateId:'minecraft-java',location:'smoke',nodeId:n1.id,memoryMb:512,cpuPercent:100,diskMb:2048,port:25565}),409,'port collision');
const second=ok(await call('POST','/api/servers',{name:'Valheim',ownerId:customer.id,templateId:'valheim',location:'smoke',nodeId:n2.id,memoryMb:512,cpuPercent:100,diskMb:2048,port:2456}),'valheim create');
const j=ok(await call('GET','/api/agent/jobs',undefined,n1.headers),'agent poll').job;if(j?.kind!=='create'||j.server?.id!==server.id)throw Error('wrong leased job');count++;ok(await call('POST',`/api/agent/jobs/${j.id}/result`,{attempt:j.attempt,success:true,result:{existing:false}},n1.headers),'job complete');const after=ok(await call('GET',`/api/servers/${server.id}`),'server status');if(after.observedStatus!=='running')throw Error('job status not persisted');count++;
ok(await call('POST','/api/agent/heartbeat',{version:'test',servers:[{id:server.id,status:'running',usage:{cpuPercent:42.5,memoryBytes:268435456,memoryLimitBytes:536870912}}]},n1.headers),'resource heartbeat');const sampled=ok(await call('GET',`/api/servers/${server.id}`),'resource detail');if(sampled.usage?.cpuPercent!==42.5||sampled.usage?.memoryBytes!==268435456||!sampled.usage?.sampledAt)throw Error('real resource heartbeat not persisted');count++;
ok(await call('POST','/api/agent/heartbeat',{version:'test',servers:[{id:server.id,status:'running'}]},n1.headers),'missing sample heartbeat');const preserved=ok(await call('GET',`/api/servers/${server.id}`),'preserved resource detail');if(preserved.usage?.cpuPercent!==42.5)throw Error('missing sample erased prior measurement');count++;
const adminCookie=cookie;cookie='';ok(await call('POST','/api/auth/login',{email:other.email,password:other.temporaryPassword}),'other login');status(await call('GET',`/api/servers/${server.id}`),404,'cross-customer metadata denied');status(await call('GET',`/api/servers/${server.id}/files?path=/`),404,'cross-customer files denied');status(await call('GET',`/api/servers/${server.id}/backups`),404,'cross-customer backups denied');const outsiderCookie=cookie;cookie=adminCookie;
count+=await liveTests({base,serverId:server.id,adminCookie,otherCookie:outsiderCookie,node1:n1,node2:n2,call});
const nodes=ok(await call('GET','/api/nodes'),'node list');if(nodes.length!==2||nodes[0].reserved.memoryMb!==512||nodes[1].reserved.memoryMb!==512)throw Error('reservations not reflected');count++;
const jobs=ok(await call('GET',`/api/jobs?serverId=${server.id}`),'job list');if(jobs[0]?.state!=='succeeded')throw Error('job status not listed');count++;
const burst=await Promise.all(Array.from({length:5},(_,i)=>call('POST','/api/servers',{name:'burst-'+i,ownerId:customer.id,templateId:'minecraft-java',location:'smoke',nodeId:n1.id,memoryMb:512,cpuPercent:100,diskMb:2048})));const accepted=burst.filter(r=>r.code===200),rejected=burst.filter(r=>r.code===409);if(accepted.length!==2||rejected.length!==3||new Set(accepted.map(r=>r.data.port)).size!==2)throw Error('concurrent placement overbooked or collided: '+JSON.stringify(burst));count++;const afterBurst=ok(await call('GET','/api/nodes'),'post-burst reservations');if(afterBurst.find(n=>n.id===n1.id)?.reserved.memoryMb!==1536)throw Error('concurrent reservations wrong');count++;
const tok=ok(await call('POST','/api/tokens',{name:'smoke integration',scopes:['provision','read','suspend']}),'scoped token');cookie='';const bearer={authorization:'Bearer '+tok.token};status(await call('GET','/api/nodes',undefined,bearer),403,'token cannot inspect nodes');status(await call('POST','/api/nodes',{name:'intruder'},bearer),403,'token cannot create nodes');status(await call('POST',`/api/servers/${server.id}/actions`,{action:'stop'},bearer),403,'token cannot stop server');ok(await call('POST',`/api/servers/${server.id}/actions`,{action:'suspend'},bearer),'token suspend');cookie=adminCookie;status(await call('DELETE',`/api/servers/${server.id}`),400,'delete confirmation');cookie='';ok(await call('POST','/api/auth/login',{email:customer.email,password:customer.temporaryPassword}),'owner login');ok(await call('PATCH',`/api/servers/${server.id}/settings`,{variables:{MOTD:'Smoke test'}}),'customer settings');status(await call('PATCH',`/api/servers/${server.id}/settings`,{variables:{EULA:'FALSE'}}),400,'customer setting whitelist');const ownerDetail=ok(await call('GET',`/api/servers/${server.id}`),'owner detail');if(!ownerDetail.variables?.RCON_PASSWORD||ownerDetail.effectivePermissions.length!==5)throw Error('owner secret/permissions missing');count++;
cookie=adminCookie;const adminDetail=ok(await call('GET',`/api/servers/${server.id}`),'admin detail');if(!adminDetail.variables?.RCON_PASSWORD)throw Error('admin secret missing');count++;
cookie='';const tokenDetail=ok(await call('GET',`/api/servers/${server.id}`,undefined,bearer),'read-token detail');if('variables' in tokenDetail||JSON.stringify(tokenDetail).includes(adminDetail.variables.RCON_PASSWORD)||JSON.stringify(tokenDetail.effectivePermissions)!==JSON.stringify(['view']))throw Error('read token exposes server secret or write permissions');count++;
const tokenTemplates=ok(await call('GET','/api/templates',undefined,bearer),'read-token templates');if(tokenTemplates.find(t=>t.id==='minecraft-java')?.env?.EULA!=='[configured]')throw Error('read token exposes template env');count++;
cookie=adminCookie;const mixed=ok(await call('GET',`/api/servers/${server.id}`,undefined,bearer),'bearer with admin cookie');if('variables' in mixed||JSON.stringify(mixed.effectivePermissions)!==JSON.stringify(['view']))throw Error('cookie bypassed bearer token restriction');count++;
for(const [grants,allowed] of [[[],false],[['view'],true],[['console'],true],[['files'],true],[['backups'],true],[['manage'],true]]){
 ok(await call('POST',`/api/servers/${server.id}/collaborators`,{email:other.email,permissions:grants}),'set collaborator grant');
 cookie='';ok(await call('POST','/api/auth/login',{email:other.email,password:other.temporaryPassword}),'collaborator login');
 const detail=await call('GET',`/api/servers/${server.id}`),listed=ok(await call('GET','/api/servers'),'collaborator list'),visible=listed.some(s=>s.id===server.id);
 if(visible!==allowed)throw Error('list/detail visibility disagreement for '+grants);count++;
 if(!allowed){status(detail,404,'empty grant detail denied');const hidden=ok(await call('GET',`/api/jobs?serverId=${server.id}`),'empty grant jobs');if(hidden.length)throw Error('empty grant reveals jobs');count++;}
 else {const d=ok(detail,'granted detail');const expected=grants.includes('manage')?['view','console','files','backups','manage']:grants;if(JSON.stringify(d.effectivePermissions)!==JSON.stringify(expected)||('variables' in d)!==grants.includes('manage'))throw Error('incorrect effective permissions/secret visibility for '+grants);count++;const visibleJobs=ok(await call('GET',`/api/jobs?serverId=${server.id}`),'granted jobs');if(!visibleJobs.length)throw Error('granted user cannot inspect jobs');count++;}
 const canBackups=grants.includes('backups')||grants.includes('manage');if(canBackups)ok(await call('GET',`/api/servers/${server.id}/backups`),'granted backups');else status(await call('GET',`/api/servers/${server.id}/backups`),404,'backups not implied by detail');
 if(!grants.includes('files')&&!grants.includes('manage'))status(await call('GET',`/api/servers/${server.id}/files?path=/`),404,'files not implied by detail');
 if(!grants.includes('console')&&!grants.includes('manage'))status(await call('GET',`/api/servers/${server.id}/console`),404,'console not implied by detail');
 if(!grants.includes('manage'))status(await call('PATCH',`/api/servers/${server.id}/settings`,{variables:{MOTD:'Unauthorized'}}),404,'manage not implied by detail');
 cookie=adminCookie;
}
if(process.env.S3_BUCKET&&process.env.S3_ACCESS_KEY&&process.env.S3_SECRET_KEY){
 // Synthetic completed backup: no S3 request is made; test only source authorization.
 const testdb=new pg.Client({connectionString:process.env.DATABASE_URL});await testdb.connect();let backupId;try{backupId=(await testdb.query("INSERT INTO backups(server_id,object_key,state) VALUES($1,$2,'succeeded') RETURNING id",[second.id,'smoke/'+randomBytes(16).toString('hex')])).rows[0].id;}finally{await testdb.end();}
 cookie='';ok(await call('POST','/api/auth/login',{email:other.email,password:other.temporaryPassword}),'manage collaborator login');status(await call('POST',`/api/servers/${server.id}/actions`,{action:'restore',backupId,confirm:true}),404,'private source backup denied to target manager');
 cookie=adminCookie;ok(await call('POST',`/api/servers/${second.id}/collaborators`,{email:other.email,permissions:['backups']}),'grant source backup access');
 cookie='';ok(await call('POST','/api/auth/login',{email:other.email,password:other.temporaryPassword}),'backup collaborator login');ok(await call('POST',`/api/servers/${server.id}/actions`,{action:'restore',backupId,confirm:true}),'authorized shared-source restore queued');cookie=adminCookie;
 // Exercise the actual authenticated, streamed agent/S3 and browser/S3 paths.
 const transferDb=new pg.Client({connectionString:process.env.DATABASE_URL});await transferDb.connect();let transferBackupId,uploadJobId,restoreJobId;const objectKey='smoke/stream/'+randomBytes(16).toString('hex');try{
  transferBackupId=(await transferDb.query("INSERT INTO backups(server_id,object_key,state) VALUES($1,$2,'running') RETURNING id",[server.id,objectKey])).rows[0].id;
  uploadJobId=(await transferDb.query("INSERT INTO jobs(node_id,server_id,kind,state,attempt,lease_until,payload) VALUES($1,$2,'backup','running',1,now()+interval '2 minutes',$3) RETURNING id",[n1.id,server.id,JSON.stringify({backupId:transferBackupId})])).rows[0].id;
  await transferDb.query('UPDATE backups SET job_id=$1 WHERE id=$2',[uploadJobId,transferBackupId]);
  restoreJobId=(await transferDb.query("INSERT INTO jobs(node_id,server_id,kind,state,attempt,lease_until,payload) VALUES($1,$2,'restore','running',1,now()+interval '2 minutes',$3) RETURNING id",[n1.id,server.id,JSON.stringify({backupId:transferBackupId})])).rows[0].id;
 }finally{await transferDb.end();}
 const archive=Buffer.from('navrylo-streamed-backup-fixture');const put=await fetch(`${base}/api/agent/jobs/${uploadJobId}/backup-object?attempt=1`,{method:'PUT',headers:{...n1.headers,'content-type':'application/octet-stream'},body:archive});if(put.status!==200)throw Error(`streamed agent backup upload: ${put.status} ${await put.text()}`);count++;
 const denied=await fetch(`${base}/api/agent/jobs/${uploadJobId}/backup-object?attempt=1`,{method:'PUT',headers:{...n2.headers,'content-type':'application/octet-stream'},body:archive});status({code:denied.status},409,'foreign node backup upload denied');
 const get=await fetch(`${base}/api/agent/jobs/${restoreJobId}/backup-object?attempt=1`,{headers:n1.headers});if(get.status!==200)throw Error(`streamed agent restore download: ${get.status} ${await get.text()}`);if(!Buffer.from(await get.arrayBuffer()).equals(archive))throw Error('agent backup round-trip changed bytes');count++;
 const completeDb=new pg.Client({connectionString:process.env.DATABASE_URL});await completeDb.connect();try{await completeDb.query("UPDATE backups SET state='succeeded',size_bytes=$1 WHERE id=$2",[archive.length,transferBackupId]);}finally{await completeDb.end();}
 const browser=await fetch(`${base}/api/servers/${server.id}/backups/${transferBackupId}/download`,{headers:{cookie:adminCookie}});if(browser.status!==200)throw Error(`browser backup download: ${browser.status}`);if(!Buffer.from(await browser.arrayBuffer()).equals(archive))throw Error('browser backup download changed bytes');count++;
 const leaseDb=new pg.Client({connectionString:process.env.DATABASE_URL});await leaseDb.connect();try{await leaseDb.query("UPDATE jobs SET lease_until=now()-interval '1 second' WHERE id=$1",[restoreJobId]);}finally{await leaseDb.end();}
 status({code:(await fetch(`${base}/api/agent/jobs/${restoreJobId}/backup-object?attempt=1`,{headers:n1.headers})).status},409,'expired backup download lease denied');
}
// Exercise expired lease and stale-attempt rejection directly against the disposable DB.
const leaseJob=ok(await call('GET','/api/agent/jobs',undefined,n2.headers),'lease job').job;if(!leaseJob||leaseJob.kind!=='create')throw Error('missing second-node create job');count++;
if(!process.env.DATABASE_URL)throw Error('DATABASE_URL needed for disposable lease-expiry test');
const db=new pg.Client({connectionString:process.env.DATABASE_URL});await db.connect();try{await db.query("UPDATE jobs SET lease_until=now()-interval '1 second' WHERE id=$1",[leaseJob.id]);}finally{await db.end();}
status(await call('POST',`/api/agent/jobs/${leaseJob.id}/renew`,{attempt:leaseJob.attempt},n2.headers),409,'expired lease renewal denied');
status(await call('POST',`/api/agent/jobs/${leaseJob.id}/result`,{attempt:leaseJob.attempt,success:true},n2.headers),409,'expired lease result denied');
const retry=ok(await call('GET','/api/agent/jobs',undefined,n2.headers),'retry claim').job;if(retry?.id!==leaseJob.id||retry.attempt!==leaseJob.attempt+1)throw Error('expired lease not reclaimed');count++;
status(await call('POST',`/api/agent/jobs/${leaseJob.id}/result`,{attempt:leaseJob.attempt,success:true},n2.headers),409,'old attempt result denied');
ok(await call('POST',`/api/agent/jobs/${retry.id}/result`,{attempt:retry.attempt,success:true},n2.headers),'retry result accepted');
// Deletion must fence later user mutations and retire queued work, not recreate an orphan.
cookie=adminCookie;const doomed=ok(await call('POST','/api/servers',{name:'Disposable',ownerId:customer.id,templateId:'minecraft-java',nodeId:n2.id,memoryMb:512,cpuPercent:100,diskMb:2048,port:25677}),'disposable server');
const createDoomed=ok(await call('GET','/api/agent/jobs',undefined,n2.headers),'disposable create claim').job;if(createDoomed?.server?.id!==doomed.id)throw Error('wrong disposable create');count++;
ok(await call('POST',`/api/agent/jobs/${createDoomed.id}/result`,{attempt:createDoomed.attempt,success:true},n2.headers),'disposable created');
ok(await call('POST',`/api/servers/${doomed.id}/actions`,{action:'stop'}),'prior stop queued');
const deletion=ok(await call('DELETE',`/api/servers/${doomed.id}?confirm=true`),'request deletion');status(await call('DELETE',`/api/servers/${doomed.id}?confirm=true`),409,'duplicate deletion fenced');
cookie='';ok(await call('POST','/api/auth/login',{email:customer.email,password:customer.temporaryPassword}),'owner login for deletion fence');status(await call('POST',`/api/servers/${doomed.id}/actions`,{action:'start'}),409,'action fenced during deletion');status(await call('PATCH',`/api/servers/${doomed.id}/settings`,{variables:{MOTD:'orphan'}}),409,'configure fenced during deletion');
cookie=adminCookie;const db2=new pg.Client({connectionString:process.env.DATABASE_URL});await db2.connect();let queuedId;try{queuedId=(await db2.query("INSERT INTO jobs(node_id,server_id,kind) VALUES($1,$2,'configure') RETURNING id",[n2.id,doomed.id])).rows[0].id;}finally{await db2.end();}
const priorJob=ok(await call('GET','/api/agent/jobs',undefined,n2.headers),'prior stop claim').job;if(priorJob?.kind!=='stop'||priorJob.server?.id!==doomed.id)throw Error('prior stop was not claimed');count++;
const parallel=ok(await call('GET','/api/agent/jobs',undefined,n2.headers),'parallel same-server poll');if(parallel.job!==null)throw Error('delete job claimed while earlier stop still running');count++;
ok(await call('POST',`/api/agent/jobs/${priorJob.id}/result`,{attempt:priorJob.attempt,success:true},n2.headers),'prior stop completed');
const stillDeleting=ok(await call('GET',`/api/servers/${doomed.id}`),'pending deletion detail');if(stillDeleting.observedStatus!=='deleting')throw Error('earlier result cleared deletion fence');count++;
status(await call('POST',`/api/servers/${doomed.id}/actions`,{action:'start'}),409,'deletion fence survives prior result');
const deletionJob=ok(await call('GET','/api/agent/jobs',undefined,n2.headers),'delete claim').job;if(deletionJob?.id!==deletion.jobId)throw Error('deletion was not claimed next');count++;
ok(await call('POST',`/api/agent/jobs/${deletionJob.id}/result`,{attempt:deletionJob.attempt,success:true},n2.headers),'delete complete');
const db3=new pg.Client({connectionString:process.env.DATABASE_URL});await db3.connect();try{const cancelled=(await db3.query('SELECT state FROM jobs WHERE id=$1',[queuedId])).rows[0];if(cancelled?.state!=='failed')throw Error('queued work survived deletion');count++;const late=(await db3.query("INSERT INTO jobs(node_id,server_id,kind) VALUES($1,$2,'configure') RETURNING id",[n2.id,doomed.id])).rows[0].id;const poll=ok(await call('GET','/api/agent/jobs',undefined,n2.headers),'orphan job rejected');if(poll.job!==null)throw Error('agent received work for deleted server');count++;const stale=(await db3.query('SELECT state FROM jobs WHERE id=$1',[late])).rows[0];if(stale?.state!=='failed')throw Error('stale job not failed');count++;}finally{await db3.end();}
console.log(`PASS ${count} assertions: auth/2FA, enrollment, heartbeat, placement, collision, durable jobs, lease fencing, isolation, scoped-token redaction, collaborator authorization, settings`);
