// Generates the reference pages from the repository sources, so they cannot drift from the code:
//   - API reference           from generated/openapi.json (see snapshot-openapi.mjs)
//   - environment variables   from .env.example, compose.yaml usage and scripts/env-descriptions.json
//   - plugin permissions etc. from api/src/plugins/manifest.ts and the plugin host limits
//   - notification events     from api/src/notifications.ts
//   - email templates         from api/src/email-defaults.ts
//   - database schema         from db/schema.sql
//   - agent job kinds         from agent/main.go and scripts/job-descriptions.json
//   - theme tokens, presets   from shared/theme.ts
//   - release notes           from docs/releases/*.md
//
//   node ../api/node_modules/tsx/dist/cli.mjs scripts/generate.ts
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { EVENTS } from '../../api/src/notifications.ts';
import { TEMPLATES, COMMON_VARS } from '../../api/src/email-defaults.ts';
import { KNOWN_HOOKS, FIXED_PERMISSIONS, describePermission, API_VERSION } from '../../api/src/plugins/manifest.ts';
import { defaultLimits } from '../../plugins/host/src/sandbox.ts';
import { COLOR_TOKENS, DENSITIES, FONTS, PRESETS, RADII, TEXT_SCALES, checkTokens, derivePalette, FLEDGE_DARK_INPUT, FLEDGE_LIGHT_INPUT } from '../../shared/theme.ts';

const here = dirname(fileURLToPath(import.meta.url));
const site = join(here, '..');
const repo = join(site, '..');
const docs = join(site, 'docs');
const read = (...p: string[]) => readFileSync(join(repo, ...p), 'utf8').replace(/\r\n/g, '\n');
const out = (path: string, text: string) => {
  const file = join(docs, path);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, text.endsWith('\n') ? text : text + '\n');
};
const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const GENERATED = (what: string) => `<!-- Generated by docs-site/scripts/generate.ts from ${what}. Do not edit by hand. -->\n`;
const problems: string[] = [];

// ---------------------------------------------------------------------------------------------------------------------------
// Release notes
// ---------------------------------------------------------------------------------------------------------------------------
{
  const dir = join(repo, 'docs', 'releases');
  rmSync(join(docs, 'releases'), { recursive: true, force: true });
  const names = readdirSync(dir).filter((f) => /^v\d.*\.md$/.test(f)).sort((a, b) => b.localeCompare(a, undefined, { numeric: true }));
  const GH = 'https://github.com/kavaliersdelikt/fledge/blob/main/';
  for (const f of names) {
    let text = read('docs', 'releases', f);
    const version = f.replace(/\.md$/, '');
    // Links to other repository files become GitHub links; links between release notes stay local.
    text = text.replace(/\]\((?!https?:|#|\/|mailto:)([^)\s]+)\)/g, (_m, target: string) => {
      if (/^v\d[^/]*\.md(#.*)?$/.test(target)) return `](${target.replace(/\.md/, '')})`;
      const clean = target.replace(/^(\.\.\/)+/, '').replace(/^\.\//, '');
      return `](${GH}${clean.startsWith('docs/') || !target.startsWith('..') ? (target.startsWith('..') ? clean : 'docs/releases/' + clean) : clean})`;
    });
    // Stray angle brackets outside code would be parsed as HTML by the site generator.
    text = text.split(/(```[\s\S]*?```)/g).map((part, i) => (i % 2 ? part : part.replace(/<(?![/a-zA-Z!])/g, '&lt;'))).join('');
    out(`releases/${f}`, `---\ntitle: ${version}\n---\n\n${text}`);
  }
  out('releases/index.md', `---\ntitle: Release notes\n---\n\n# Release notes\n\n${GENERATED('docs/releases/*.md')}\nFledge versions have four parts: \`major.minor.patch.release\`. Notes for every release:\n\n${names.map((f) => `- [${f.replace(/\.md$/, '')}](/releases/${f.replace(/\.md$/, '')})`).join('\n')}\n\nThe newest release is also on the [GitHub releases page](https://github.com/kavaliersdelikt/fledge/releases).\n`);
}

// ---------------------------------------------------------------------------------------------------------------------------
// Environment variables
// ---------------------------------------------------------------------------------------------------------------------------
{
  type Desc = { scope: string; group: string; default?: string; description: string };
  const described: Record<string, Desc> = JSON.parse(readFileSync(join(here, 'env-descriptions.json'), 'utf8'));
  delete (described as any)._comment;
  const example = read('.env.example');
  const inExample = new Map<string, { value: string; commented: boolean }>();
  for (const line of example.split('\n')) {
    const m = /^(#\s*)?([A-Z][A-Z0-9_]+)=(.*)$/.exec(line);
    if (m) inExample.set(m[2], { value: m[3].replace(/\s+#.*$/, '').trim(), commented: !!m[1] });
  }
  // Every variable the code reads must be described.
  const used = new Set<string>();
  const scan = (text: string, re: RegExp) => { for (const m of text.matchAll(re)) used.add(m[1]); };
  const walk = (dir: string, exts: string[]) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      if (e.name === 'node_modules' || e.name === 'test' || e.name.startsWith('.')) continue;
      const p = join(dir, e.name);
      if (e.isDirectory()) walk(p, exts);
      else if (exts.some((x) => e.name.endsWith(x)) && !e.name.endsWith('_test.go')) {
        const t = readFileSync(p, 'utf8');
        scan(t, /process\.env\.([A-Z][A-Z0-9_]+)/g);
        scan(t, /\be\.([A-Z][A-Z0-9_]{3,})\b/g);
        scan(t, /(?:os\.Getenv|env)\("([A-Z][A-Z0-9_]+)"/g);
      }
    }
  };
  walk(join(repo, 'api', 'src'), ['.ts']);
  walk(join(repo, 'plugins', 'host', 'src'), ['.ts']);
  walk(join(repo, 'agent'), ['.go']);
  scan(read('compose.yaml'), /\$\{([A-Z][A-Z0-9_]+)[:?-]/g);
  for (const k of inExample.keys()) used.add(k);
  for (const k of [...used].sort()) if (!described[k]) problems.push(`environment variable ${k} is used but has no entry in scripts/env-descriptions.json`);
  for (const k of Object.keys(described)) if (!used.has(k) && !['INSTALL_PLUGIN_WAIT_ATTEMPTS', 'UPDATE_POLL_SECONDS', 'FLEDGE_DOCKER_TEST_IMAGE'].includes(k)) problems.push(`environment variable ${k} is described but no longer used`);

  const groups: [string, string, string][] = [
    ['required', 'Required', 'Set these in `.env` before the first start.'],
    ['deployment', 'Deployment', 'Set in `.env` when your setup needs them.'],
    ['seed', 'Optional seeds', 'These only seed a form in the panel before it is first saved there; afterwards the database wins.'],
    ['process', 'Set by Compose or the image', 'Normally not edited. Listed for people running the API outside Compose.'],
    ['agent', 'Node agent', 'Environment of the `fledge-agent` service on a node (the connector writes them into the unit).'],
    ['test', 'Test switches', '**Never set these in production.** They exist for the test suites.'],
  ];
  let md = `---\ntitle: Environment variables\n---\n\n# Environment variables\n\n${GENERATED('.env.example, compose.yaml, scripts/env-descriptions.json and a scan of the code')}\n`;
  md += 'Every variable the code reads is listed. See [Configuration](/operate/configuration) for how the pieces fit.\n';
  for (const [key, title, intro] of groups) {
    const items = Object.entries(described).filter(([, d]) => d.group === key).sort(([a], [b]) => a.localeCompare(b));
    if (!items.length) continue;
    md += `\n## ${title}\n\n${intro}\n\n| Variable | Used by | Default | Meaning |\n| --- | --- | --- | --- |\n`;
    for (const [name, d] of items) {
      const ex = inExample.get(name);
      const def = d.default ?? (ex && ex.value && !/REPLACE_WITH/.test(ex.value) ? ex.value : '');
      md += `| \`${name}\` | ${d.scope} | ${def ? `\`${esc(def)}\`` : ''} | ${esc(d.description)} |\n`;
    }
  }
  out('reference/environment.md', md);
}

// ---------------------------------------------------------------------------------------------------------------------------
// Plugin permissions, hooks, limits
// ---------------------------------------------------------------------------------------------------------------------------
{
  const mb = (n: number) => `${Math.round((n / (1 << 20)) * 10) / 10} MB`;
  let md = `---\ntitle: Plugin permissions and hooks\n---\n\n# Plugin permissions, hooks and limits\n\n${GENERATED('api/src/plugins/manifest.ts and plugins/host/src/sandbox.ts')}\nPlugin API version: **${API_VERSION}**. See [Manifest and permissions](/plugins/manifest) for how to use them.\n\n`;
  md += '## Permissions\n\n| Permission | What the administrator is told |\n| --- | --- |\n';
  md += `| \`network:<host>\` | ${esc(describePermission('network:example.org').replace('example.org', 'the named host'))}. \`<host>\` is a full domain or \`*.domain\`; wildcards over shared hosting platforms are refused |\n`;
  for (const p of FIXED_PERMISSIONS) md += `| \`${p}\` | ${esc(describePermission(p))} |\n`;
  md += '\n## Hooks\n\nA plugin needs the `hooks` permission to receive them.\n\n| Event |\n| --- |\n';
  for (const h of KNOWN_HOOKS) md += `| \`${h}\` |\n`;
  md += '\n## Setting field types\n\n`string` (`pattern`, `placeholder`), `number` (`min`, `max`), `boolean`, `select` (`options`), `secret` (encrypted at rest, write-only).\n';
  md += '\n## Sandbox limits per call\n\n| Limit | Value |\n| --- | --- |\n';
  md += `| Memory | ${mb(defaultLimits.memoryBytes)} |\n| Stack | ${mb(defaultLimits.stackBytes)} |\n| Run time | ${defaultLimits.deadlineMs / 1000} s |\n| Requests | ${defaultLimits.maxFetches} |\n| Bytes per response | ${mb(defaultLimits.maxFetchBytes)} |\n| Bytes per call (all responses) | ${mb(defaultLimits.maxTotalBytes)} |\n| Result size | ${mb(defaultLimits.maxResultBytes)} |\n| Log lines | ${defaultLimits.maxLogLines} |\n| Storage | ${Math.round(defaultLimits.maxStorageBytes / 1024)} KB |\n`;
  out('reference/plugin-manifest.md', md);
}

// ---------------------------------------------------------------------------------------------------------------------------
// Notification events
// ---------------------------------------------------------------------------------------------------------------------------
{
  let md = `---\ntitle: Notification events\n---\n\n# Notification events\n\n${GENERATED('api/src/notifications.ts')}\n`;
  md += 'Every event can be sent to the inbox and to any [channel](/panel/notifications). *Scope* says whether it is about a server (customers see events for their own servers) or about the panel (administrators only). Webhook bodies are described in [Webhook payloads](/api/webhooks).\n\n| Event | Meaning | Scope | Severity |\n| --- | --- | --- | --- |\n';
  for (const e of EVENTS) md += `| \`${e.id}\` | ${esc(e.label)} | ${e.scope} | ${e.severity} |\n`;
  out('reference/events.md', md);
}

// ---------------------------------------------------------------------------------------------------------------------------
// Email templates
// ---------------------------------------------------------------------------------------------------------------------------
{
  let md = `---\ntitle: Email templates and variables\n---\n\n# Email templates and variables\n\n${GENERATED('api/src/email-defaults.ts')}\n`;
  md += 'Every email the panel sends, with the values you can use in it. Edit them under [Settings → Email templates](/panel/email-templates). Write a value as `{{name}}`; show text only when a value exists with `{{#if name}}…{{/if}}`.\n\n';
  md += '## Available in every template\n\n| Variable | Meaning | Example |\n| --- | --- | --- |\n';
  for (const v of COMMON_VARS) md += `| \`{{${v.name}}}\` | ${esc(v.help)} | ${esc(v.sample)} |\n`;
  for (const group of ['Account', 'Billing', 'Limits', 'Administrators', 'System'] as const) {
    md += `\n## ${group}\n`;
    for (const t of TEMPLATES.filter((x) => x.group === group)) {
      md += `\n### ${t.label}\n\n\`${t.id}\` · to ${t.audience === 'admin' ? 'administrators' : 'the customer'} · ${t.critical ? 'always sent' : 'can be switched off'}${t.bccAdmin ? ' · a copy goes to the copy address' : ''}\n\n${t.description}\n\n`;
      if (t.vars.length) {
        md += '| Variable | Meaning | Example |\n| --- | --- | --- |\n';
        for (const v of t.vars) md += `| \`{{${v.name}}}\` | ${esc(v.help)} | ${esc(v.sample)} |\n`;
        md += '\n';
      }
      md += `Subject: \`${t.subject}\`\n\n\`\`\`text\n${t.body}\n\`\`\`\n`;
    }
  }
  // The templates are full of {{values}}, which the page generator would otherwise try to evaluate.
  const marker = 'Every email the panel sends';
  const [head, ...rest] = md.split(marker);
  out('reference/email-templates.md', `${head}<div v-pre>\n\n${marker}${rest.join(marker)}\n</div>\n`);
}

// ---------------------------------------------------------------------------------------------------------------------------
// Database schema
// ---------------------------------------------------------------------------------------------------------------------------
{
  const sql = read('db', 'schema.sql');
  type Col = { name: string; type: string; later: boolean };
  const tables = new Map<string, { cols: Col[]; note: string }>();
  const splitTop = (s: string) => {
    const parts: string[] = []; let depth = 0, cur = '';
    for (const ch of s) {
      if (ch === '(') depth++;
      if (ch === ')') depth--;
      if (ch === ',' && depth === 0) { parts.push(cur); cur = ''; } else cur += ch;
    }
    if (cur.trim()) parts.push(cur);
    return parts;
  };
  const re = /((?:--[^\n]*\n)*)\s*CREATE TABLE IF NOT EXISTS\s+([a-z_]+)\s*\(/gi;
  for (let m; (m = re.exec(sql)); ) {
    let depth = 1, i = re.lastIndex;
    while (i < sql.length && depth > 0) { if (sql[i] === '(') depth++; else if (sql[i] === ')') depth--; i++; }
    const body = sql.slice(re.lastIndex, i - 1).replace(/--[^\n]*/g, '');
    const cols: Col[] = [];
    for (const part of splitTop(body)) {
      const t = part.trim().replace(/\s+/g, ' ');
      if (!t || /^(PRIMARY|UNIQUE|FOREIGN|CHECK|CONSTRAINT)\b/i.test(t)) continue;
      const mm = /^([a-z_][a-z0-9_]*)\s+(.*)$/i.exec(t);
      if (mm) cols.push({ name: mm[1], type: mm[2].split(/\s+(?:NOT NULL|NULL|DEFAULT|PRIMARY|REFERENCES|CHECK|UNIQUE)\b/i)[0], later: false });
    }
    const note = m[1].split('\n').map((l) => l.replace(/^--\s?/, '').trim()).filter(Boolean).join(' ');
    tables.set(m[2], { cols, note });
  }
  for (const m of sql.matchAll(/ALTER TABLE\s+([a-z_]+)\s+ADD COLUMN IF NOT EXISTS\s+([a-z_][a-z0-9_]*)\s+([^,;\n]+)/gi)) {
    const t = tables.get(m[1]);
    if (t && !t.cols.some((c) => c.name === m[2])) t.cols.push({ name: m[2], type: m[3].split(/\s+(?:NOT NULL|NULL|DEFAULT|PRIMARY|REFERENCES|CHECK|UNIQUE)\b/i)[0].trim(), later: true });
  }
  let md = `---\ntitle: Database schema\n---\n\n# Database schema\n\n${GENERATED('db/schema.sql')}\n`;
  md += 'PostgreSQL 15 or newer. `db/schema.sql` is applied idempotently at API startup and is **additive**: tables and columns are created if missing and never dropped. Column types are shown as written in the schema; columns marked *added later* arrived through an `ALTER TABLE` in a newer release.\n\n';
  md += `There are **${tables.size}** tables.\n\n`;
  md += [...tables.keys()].sort().map((t) => `[\`${t}\`](#${t.replace(/_/g, '-')})`).join(' · ') + '\n';
  for (const name of [...tables.keys()].sort()) {
    const t = tables.get(name)!;
    md += `\n## ${name}\n\n${t.note ? t.note + '\n\n' : ''}| Column | Type | |\n| --- | --- | --- |\n`;
    for (const c of t.cols) md += `| \`${c.name}\` | \`${esc(c.type)}\` | ${c.later ? 'added later' : ''} |\n`;
  }
  out('reference/schema.md', md);
}

// ---------------------------------------------------------------------------------------------------------------------------
// Agent job kinds
// ---------------------------------------------------------------------------------------------------------------------------
{
  const go = read('agent', 'main.go');
  const descriptions: Record<string, string> = JSON.parse(readFileSync(join(here, 'job-descriptions.json'), 'utf8'));
  const start = go.indexOf('switch j.Kind {');
  const kinds = new Set<string>();
  for (const m of go.slice(start).matchAll(/^\tcase ((?:"[a-z.-]+"(?:, )?)+):/gm)) for (const k of m[1].matchAll(/"([a-z.-]+)"/g)) kinds.add(k[1]);
  for (const m of go.matchAll(/j\.Kind == "([a-z.-]+)"/g)) kinds.add(m[1]);
  for (const k of kinds) if (!descriptions[k]) problems.push(`agent job kind ${k} has no entry in scripts/job-descriptions.json`);
  for (const k of Object.keys(descriptions)) if (k !== '_comment' && !kinds.has(k)) problems.push(`job kind ${k} is described but the agent no longer handles it`);
  let md = `---\ntitle: Agent job kinds\n---\n\n# Agent job kinds\n\n${GENERATED('agent/main.go and scripts/job-descriptions.json')}\n`;
  md += 'Every job the panel can send to a node. The agent leases jobs one at a time per server; see the [agent protocol](/api/agent-protocol). Unknown kinds are failed with an error.\n\n| Kind | What it does |\n| --- | --- |\n';
  for (const k of [...kinds].sort()) md += `| \`${k}\` | ${esc(descriptions[k] ?? '')} |\n`;
  out('reference/jobs.md', md);
}

// ---------------------------------------------------------------------------------------------------------------------------
// API reference
// ---------------------------------------------------------------------------------------------------------------------------
{
  const specPath = join(site, 'generated', 'openapi.json');
  rmSync(join(docs, 'api', 'reference'), { recursive: true, force: true });
  if (!existsSync(specPath)) {
    problems.push('generated/openapi.json is missing: run `npm run snapshot` (needs PostgreSQL, see docs-site/README.md)');
  } else {
    const spec = JSON.parse(readFileSync(specPath, 'utf8'));
    const byTag = new Map<string, { method: string; path: string; op: any }[]>();
    for (const [path, ops] of Object.entries<any>(spec.paths)) {
      for (const [method, op] of Object.entries<any>(ops)) {
        const tag = (op.tags?.[0] as string) || 'Other';
        if (!byTag.has(tag)) byTag.set(tag, []);
        byTag.get(tag)!.push({ method: method.toUpperCase(), path, op });
      }
    }
    const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    const accessText: Record<string, string> = {
      public: 'No authentication',
      session: 'Signed-in user (browser session)',
      admin: 'Administrator',
      agent: 'Node agent credential',
      token: 'API token',
    };
    const order = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];
    const tags = [...byTag.keys()].sort((a, b) => (a.startsWith('Undocumented') ? 1 : 0) - (b.startsWith('Undocumented') ? 1 : 0) || a.localeCompare(b));
    let undocumented = 0, total = 0;
    for (const tag of tags) {
      const ops = byTag.get(tag)!.sort((a, b) => a.path.localeCompare(b.path) || order.indexOf(a.method) - order.indexOf(b.method));
      let md = `---\ntitle: ${tag.replace(/:/g, ' -')}\n---\n\n# ${tag}\n\n${GENERATED('GET /api/openapi.json')}\n`;
      for (const { method, path, op } of ops) {
        total++;
        if (op.summary === 'Undocumented') undocumented++;
        const params = (op.parameters || []).map((p: any) => `\`${p.name}\``).join(', ');
        md += `\n### ${method} \`${path}\` {#${method.toLowerCase()}-${slug(path)}}\n\n${op.summary}\n\n`;
        md += `- **Access:** ${accessText[op['x-access']] ?? op['x-access']}${op['x-token-scope'] ? `; also reachable with an API token that has the \`${op['x-token-scope']}\` scope` : ''}\n`;
        if (params) md += `- **Path parameters:** ${params}\n`;
        const body = op.requestBody?.content?.['application/json']?.schema?.description;
        if (body) md += `- **Body:** ${esc(body)}\n`;
      }
      out(`api/reference/${slug(tag)}.md`, md);
    }
    let idx = `---\ntitle: Endpoint reference\n---\n\n# Endpoint reference\n\n${GENERATED('GET /api/openapi.json')}\n`;
    idx += `Fledge **${spec.info.version}**, ${total} operations. Conventions: [Errors, paging, limits](/api/conventions); authentication: [Authentication](/api/authentication). The same description is served by the API itself at \`/api/openapi.json\` (administrators) and rendered in the panel under **API**.\n\n`;
    idx += '| Area | Operations |\n| --- | --- |\n';
    for (const tag of tags) idx += `| [${tag}](/api/reference/${slug(tag)}) | ${byTag.get(tag)!.length} |\n`;
    if (undocumented) idx += `\n${undocumented} operations are not documented yet and are listed under the *Undocumented* areas with their method and path only.\n`;
    out('api/reference/index.md', idx);
    writeFileSync(join(site, 'generated', 'coverage.json'), JSON.stringify({ total, undocumented }));
  }
}

// ---------------------------------------------------------------------------------------------------------------------------
// Theme tokens and presets (the appearance settings)
// ---------------------------------------------------------------------------------------------------------------------------
{
  const use: Record<string, string> = {
    bg: 'Page background', surface: 'Cards and panels', 'surface-2': 'Inputs, raised areas', 'surface-3': 'Hover and pressed states', raised: 'Menus, dialogs, toasts',
    border: 'Dividers and card borders', 'border-strong': 'Input and button borders', 'border-hover': 'Borders on hover',
    text: 'Body text', 'text-2': 'Secondary text', 'text-3': 'Hints, placeholders, disabled text',
    primary: 'Main button', 'primary-hover': 'Main button on hover', 'primary-text': 'Text on the main button', accent: 'Links, focus rings, switches, highlights', 'on-accent': 'The knob of a switch that is on',
    ok: 'Success', warn: 'Warning', bad: 'Error and delete', busy: 'Busy and information', 'on-bad': 'Text on a solid delete button',
    'seg-alt': 'Second colour in stacked bars', 'terminal-bg': 'Console and file editor background', 'terminal-text': 'Console text', 'shadow-ink': 'Colour of shadows', wash: 'Hover overlays (white on dark, black on light)', gloss: 'Highlight on buttons', scrim: 'Dimmed backdrop behind dialogs',
  };
  for (const t of COLOR_TOKENS) if (!use[t]) problems.push(`theme token ${t} has no description in scripts/generate.ts`);
  const dark = derivePalette(FLEDGE_DARK_INPUT, 'dark').tokens, light = derivePalette(FLEDGE_LIGHT_INPUT, 'light').tokens;
  const sw = (hex: string) => `\`${hex}\``;
  let md = `---\ntitle: Theme tokens and presets\n---\n\n# Theme tokens and presets\n\n${GENERATED('shared/theme.ts')}\n`;
  md += 'This is the reference behind [Appearance](/panel/appearance): the colours Fledge calculates, the checks it runs and the built-in presets. The same file is used by the panel (live preview) and by the API (validation), so these tables are what the code does.\n\n';
  md += '## Colour tokens\n\nEach token is a CSS custom property named `--<token>`. The first two columns are Fledge\'s own palettes; other palettes are calculated from an accent colour and a tint.\n\n| Token | Used for | Fledge dark | Fledge light |\n| --- | --- | --- | --- |\n';
  for (const t of COLOR_TOKENS) md += `| \`--${t}\` | ${use[t]} | ${sw((dark as any)[t])} | ${sw((light as any)[t])} |\n`;
  md += '\nSoft and line variants (`--accent-soft`, `--ok-soft`, `--warn-soft`, `--bad-soft`, `--busy-soft`, `--accent-line`) are always mixed from their base colour in the stylesheet, so changing a base colour changes them too.\n\n';
  const std = checkTokens(dark, 'standard'), high = checkTokens(dark, 'high');
  md += '## Readability checks\n\nEvery palette is checked before it can be saved. **Cannot be saved** means the pair fails the minimum; **Warning** only reports it. *High contrast* raises the minimums.\n\n| Pair | Minimum | Minimum (high contrast) | If it fails |\n| --- | --- | --- | --- |\n';
  for (const p of std.pairs) {
    const h = high.pairs.find((x) => x.id === p.id);
    md += `| ${p.label} | ${p.min}:1 | ${h ? `${h.min}:1` : 'n/a'} | ${p.severity === 'error' ? 'Cannot be saved' : 'Warning'} |\n`;
  }
  md += '| The four status colours | Look different with red-green colour blindness | | Warning |\n\n';
  md += 'Calculated palettes also keep hints and placeholders at 4.5:1 on every surface. The built-in Fledge dark palette is the exception: it keeps its original 3.6:1 for hints so that an untouched panel looks exactly as before, which is why the *Fledge* preset can show that row as a warning in the editor; every other preset, and *High contrast*, passes.\n\nA chosen accent that is too dim is **moved** (lighter on dark, darker on light) until the first rows pass, and the editor says so. Only colours you pin yourself, or exotic combinations, can fail.\n\n';
  md += '## Presets\n\nEvery preset has a dark and a light palette. Choosing one also sets the font, corner radius and density shown.\n\n| Preset | Description | Dark (page, accent) | Light (page, accent) | Font | Corners | Density |\n| --- | --- | --- | --- | --- | --- | --- |\n';
  for (const p of PRESETS) {
    const d = derivePalette(p.dark, 'dark').tokens, l = derivePalette(p.light, 'light').tokens;
    md += `| **${p.name}** | ${p.description} | ${sw(d.bg)}, ${sw(d.accent)} | ${sw(l.bg)}, ${sw(l.accent)} | ${FONTS[p.font ?? 'geist'].label} | ${p.radius ?? 10} px | ${p.density ?? 'comfortable'} |\n`;
  }
  md += '\n## Fonts, sizes and shape\n\n| Setting | Choices |\n| --- | --- |\n';
  md += `| Font | ${(Object.keys(FONTS) as (keyof typeof FONTS)[]).map((k) => `${FONTS[k].label} (${FONTS[k].note.toLowerCase()})`).join('; ')}. Fonts are bundled with the panel; nothing is loaded from other sites. |\n`;
  md += `| Text size | ${TEXT_SCALES.map((s) => `${Math.round(s * 100)}%`).join(', ')} (\`--text-scale\`) |\n`;
  md += `| Corner radius | ${RADII.map((r) => (r === 0 ? 'square' : `${r} px`)).join(', ')} (\`--radius-scale\`, 10 px is 1) |\n`;
  md += `| Density | ${Object.entries(DENSITIES).map(([k, v]) => `${k} (${v})`).join(', ')} (\`--density\`, scales control and row heights) |\n`;
  out('reference/theme-tokens.md', md);
}

if (problems.length) {
  console.error('Docs generation found problems:\n - ' + problems.join('\n - '));
  process.exit(1);
}
console.log('Generated the reference pages.');
