import { defineConfig } from 'vitepress';
import { existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const docs = join(here, '..');
// Served from https://<owner>.github.io/fledge/ unless DOCS_BASE says otherwise.
const base = process.env.DOCS_BASE || '/fledge/';

// Release notes and API pages are generated by `npm run generate`; list whatever exists.
function releaseItems() {
  const dir = join(docs, 'releases');
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => /^v\d.*\.md$/.test(f))
    .sort((a, b) => b.localeCompare(a, undefined, { numeric: true }))
    .map((f) => ({ text: f.replace(/\.md$/, ''), link: `/releases/${f.replace(/\.md$/, '')}` }));
}
function apiTagItems() {
  const dir = join(docs, 'api', 'reference');
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md') && f !== 'index.md')
    .sort()
    .map((f) => ({ text: f.replace(/\.md$/, '').replace(/-/g, ' '), link: `/api/reference/${f.replace(/\.md$/, '')}` }));
}

export default defineConfig({
  title: 'Fledge',
  description: 'Documentation for Fledge, the self-hosted game server panel.',
  lang: 'en-US',
  base,
  cleanUrls: true,
  lastUpdated: false,
  head: [['link', { rel: 'icon', href: `${base}fledge-symbol.png` }]],
  // localhost addresses in the docs are examples, not links to check.
  ignoreDeadLinks: [/^https?:\/\/localhost/],
  themeConfig: {
    logo: '/fledge-symbol.png',
    siteTitle: 'Fledge',
    search: { provider: 'local' },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/kavaliersdelikt/fledge' },
      { icon: 'discord', link: 'https://discord.gg/gu49ZF6tQh' },
    ],
    editLink: {
      pattern: 'https://github.com/kavaliersdelikt/fledge/edit/main/docs-site/docs/:path',
      text: 'Suggest a change to this page',
    },
    nav: [
      { text: 'Guide', link: '/guide/what-is-fledge' },
      { text: 'Operate', link: '/operate/install' },
      { text: 'Panel', link: '/panel/servers' },
      { text: 'Plugins', link: '/plugins/' },
      { text: 'API', link: '/api/' },
      { text: 'Reference', link: '/reference/' },
      {
        text: 'More',
        items: [
          { text: 'Node agent', link: '/agent/' },
          { text: 'Security', link: '/security/' },
          { text: 'Development', link: '/dev/' },
          { text: 'Release notes', link: '/releases/' },
        ],
      },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Start here',
          items: [
            { text: 'What is Fledge?', link: '/guide/what-is-fledge' },
            { text: 'Concepts', link: '/guide/concepts' },
            { text: 'Quickstart', link: '/guide/quickstart' },
            { text: 'Status and known gaps', link: '/guide/status' },
          ],
        },
      ],
      '/operate/': [
        {
          text: 'Install and operate',
          items: [
            { text: 'Install', link: '/operate/install' },
            { text: 'Configuration', link: '/operate/configuration' },
            { text: 'Reverse proxy and TLS', link: '/operate/reverse-proxy' },
            { text: 'Updating and rollback', link: '/operate/updating' },
            { text: 'Backups and object storage', link: '/operate/backups' },
            { text: 'Failover and moves', link: '/operate/failover' },
            { text: 'Email', link: '/operate/email' },
            { text: 'Monitoring', link: '/operate/monitoring' },
            { text: 'Recovering from a bad theme', link: '/operate/branding-recovery' },
            { text: 'Troubleshooting', link: '/operate/troubleshooting' },
          ],
        },
      ],
      '/panel/': [
        {
          text: 'Servers',
          items: [
            { text: 'Servers and console', link: '/panel/servers' },
            { text: 'Files and SFTP', link: '/panel/files' },
            { text: 'Resources and disk limits', link: '/panel/resources' },
            { text: 'Startup panel', link: '/panel/startup' },
            { text: 'Extra ports', link: '/panel/ports' },
            { text: 'Backups and restore', link: '/panel/backups' },
            { text: 'Clone a server', link: '/panel/clone' },
            { text: 'Mods and plugins (add-ons)', link: '/panel/addons' },
          ],
        },
        {
          text: 'Autopilot',
          items: [
            { text: 'Schedules', link: '/panel/schedules' },
            { text: 'Crash protection', link: '/panel/crash-protection' },
            { text: 'Notifications', link: '/panel/notifications' },
            { text: 'Usage history', link: '/panel/usage-history' },
          ],
        },
        {
          text: 'Administration',
          items: [
            { text: 'Nodes', link: '/panel/nodes' },
            { text: 'Customers and quotas', link: '/panel/customers' },
            { text: 'Templates', link: '/panel/templates' },
            { text: 'Settings', link: '/panel/settings' },
            { text: 'Appearance', link: '/panel/appearance' },
            { text: 'Account security', link: '/panel/account-security' },
            { text: 'Audit log', link: '/panel/audit' },
          ],
        },
      ],
      '/agent/': [
        {
          text: 'Node agent',
          items: [
            { text: 'Overview', link: '/agent/' },
            { text: 'Connect a node', link: '/agent/connect' },
            { text: 'WSL2 evaluation node', link: '/agent/wsl2' },
            { text: 'Disk limits and volumes', link: '/agent/disk-limits' },
            { text: 'Console and stopping', link: '/agent/console' },
            { text: 'Agent updates', link: '/agent/updates' },
          ],
        },
      ],
      '/plugins/': [
        {
          text: 'Using plugins',
          items: [
            { text: 'Overview', link: '/plugins/' },
            { text: 'Using the store', link: '/plugins/using' },
            { text: 'The bundled plugins', link: '/plugins/bundled' },
          ],
        },
        {
          text: 'Writing plugins',
          items: [
            { text: 'Tutorial: your first catalog', link: '/plugins/tutorial' },
            { text: 'Manifest and permissions', link: '/plugins/manifest' },
            { text: 'Catalog contract', link: '/plugins/catalog' },
            { text: 'The host API', link: '/plugins/host-api' },
            { text: 'Hooks', link: '/plugins/hooks' },
            { text: 'Packaging, signing, registry', link: '/plugins/packaging' },
            { text: 'Testing', link: '/plugins/testing' },
            { text: 'Limits', link: '/plugins/limits' },
          ],
        },
        { text: 'Security', items: [{ text: 'Security model', link: '/plugins/security' }] },
      ],
      '/api/reference/': [
        { text: 'API', items: [{ text: 'Back to the API overview', link: '/api/' }] },
        { text: 'Endpoints by area', items: [{ text: 'Index', link: '/api/reference/' }, ...apiTagItems()] },
      ],
      '/api/': [
        {
          text: 'API',
          items: [
            { text: 'Overview', link: '/api/' },
            { text: 'Authentication', link: '/api/authentication' },
            { text: 'Errors, paging, limits', link: '/api/conventions' },
            { text: 'Live console WebSocket', link: '/api/websocket' },
            { text: 'Webhook payloads', link: '/api/webhooks' },
            { text: 'Agent protocol', link: '/api/agent-protocol' },
            { text: 'Endpoint reference', link: '/api/reference/' },
          ],
        },
      ],
      '/reference/': [
        {
          text: 'Reference',
          items: [
            { text: 'Overview', link: '/reference/' },
            { text: 'Environment variables', link: '/reference/environment' },
            { text: 'Plugin permissions and hooks', link: '/reference/plugin-manifest' },
            { text: 'Notification events', link: '/reference/events' },
            { text: 'Template variable types', link: '/reference/template-variables' },
            { text: 'Theme tokens and presets', link: '/reference/theme-tokens' },
            { text: 'Database schema', link: '/reference/schema' },
            { text: 'Agent job kinds', link: '/reference/jobs' },
          ],
        },
      ],
      '/security/': [
        {
          text: 'Security',
          items: [
            { text: 'Overview and threat model', link: '/security/' },
            { text: 'Hardening checklist', link: '/security/hardening' },
            { text: 'Verifying releases', link: '/security/supply-chain' },
            { text: 'Reporting a vulnerability', link: '/security/reporting' },
          ],
        },
      ],
      '/dev/': [
        {
          text: 'Development',
          items: [
            { text: 'Repository layout', link: '/dev/' },
            { text: 'Run from source', link: '/dev/run-from-source' },
            { text: 'Tests', link: '/dev/tests' },
            { text: 'Adding an API route', link: '/dev/adding-routes' },
            { text: 'Writing these docs', link: '/dev/docs' },
            { text: 'Releasing', link: '/dev/releasing' },
          ],
        },
      ],
      '/releases/': [{ text: 'Release notes', items: [{ text: 'All releases', link: '/releases/' }, ...releaseItems()] }],
    },
    outline: { level: [2, 3] },
    footer: {
      message: 'Released under the AGPL-3.0-only license.',
      copyright: 'Fledge',
    },
  },
});
