'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Box,Copy,Plus,LoaderCircle} from 'lucide-react';
import {request,json} from '@/lib/api';
type Template={id:string;name:string;image:string;startup?:string;internalPorts:{container:number;offset:number;protocol:string}[];env:Record<string,string>;memoryMb:number;cpuPercent:number;diskMb:number;editableVariables:string[];official:boolean};
const blank={id:'my-game',name:'My game',image:'itzg/minecraft-server:java21-alpine',internalPorts:[{container:25565,offset:0,protocol:'tcp'}],env:{EULA:'TRUE',TYPE:'VANILLA',ENABLE_RCON:'TRUE'},memoryMb:2048,cpuPercent:100,diskMb:10240,editableVariables:['MOTD','MAX_PLAYERS']};
export default function Templates(){const [templates,setTemplates]=useState<Template[]>([]),[editor,setEditor]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){try{setTemplates(await request('/templates'));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await json('POST','/templates',JSON.parse(editor));setEditor('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="heading"><div><div className="eyebrow">WORKSPACE / TEMPLATES</div><h1>A starting point for every world.</h1><p className="muted">Reusable game configurations for every node in your fleet.</p></div><button className="btn primary" onClick={()=>setEditor(JSON.stringify(blank,null,2))}><Plus size={15}/>Create template</button></div>{error&&<div className="notice error" role="alert">{error}</div>}{editor&&<section className="section"><div className="section-title"><div><h2>Create a reusable template</h2><p className="muted">Choose a unique ID. Images must be allowed by your panel and agents.</p></div></div><form className="form" onSubmit={save}><label className="field"><span>Template configuration (JSON)</span><textarea className="mono" rows={20} value={editor} onChange={e=>setEditor(e.target.value)} spellCheck={false}/></label><div className="form-actions"><button className="btn primary" disabled={busy}>{busy&&<LoaderCircle size={14} className="spin"/>}Save template</button><button type="button" className="btn" onClick={()=>setEditor('')}>Cancel</button></div></form></section>}{loading?<div className="skeleton"/>:<div className="template-grid">{templates.map(t=><article className="template-card" key={t.id}><div className="template-top"><Box size={21}/><span className="muted small">{t.official?'INCLUDED':'CUSTOM'}</span></div><h2>{t.name}</h2><p className="muted mono small">{t.image}</p><div className="template-specs"><span>{t.memoryMb} MB RAM</span><span>{t.cpuPercent}% CPU</span><span>{(t.diskMb/1024).toFixed(0)} GB disk</span></div><p className="muted small">{t.internalPorts.map(p=>`${p.container}/${p.protocol}`).join(' · ')}</p><button className="btn" onClick={()=>{const {official,...draft}=t;setEditor(JSON.stringify({...draft,id:`${t.id}-custom`,name:`${t.name} custom`},null,2));window.scrollTo({top:0,behavior:'smooth'});}}><Copy size={13}/>Use as starting point</button></article>)}</div>}</>;
}
