'use client';
import {useCallback,useEffect,useState} from 'react';
import {Check,Copy,Download,ExternalLink,RefreshCw,ShieldCheck,Terminal,Wrench} from 'lucide-react';
import {request} from '@/lib/api';

type UpdateInfo={repository:string;currentVersion:string;latestVersion:string|null;updateAvailable:boolean;releaseName:string|null;releaseUrl:string;body:string;publishedAt:string|null;checkedAt:string;error:string|null};
export default function UpdateCenter(){
 const [info,setInfo]=useState<UpdateInfo|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[copied,setCopied]=useState(false),[windows,setWindows]=useState(false);
 const load=useCallback(async(force=false)=>{setLoading(true);setError('');try{setInfo(await request<UpdateInfo>(`/updates${force?'?refresh=1':''}`));}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{setWindows(/windows|win32/i.test(navigator.userAgent));load();},[load]);
 const versionArg=info?.updateAvailable&&info.latestVersion?` v${info.latestVersion}`:'';
 const command=windows?`powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\\update.ps1${versionArg?` -Version${versionArg}`:''}`:`sh ./update.sh${versionArg}`;
 async function copy(){try{await navigator.clipboard.writeText(command);setCopied(true);window.setTimeout(()=>setCopied(false),1600);}catch{setCopied(false);}}
 return <><div className="heading"><div><div className="eyebrow">OPERATIONS / RELEASES</div><h1>Panel updates</h1><p className="muted">Review releases and safely update this host from its project checkout.</p></div><button className="btn" onClick={()=>load(true)} disabled={loading}><RefreshCw size={15} className={loading?'spin':''}/> Check now</button></div>
  <section className="section update-status"><div className="update-mark"><Download size={19}/></div><div className="update-summary"><span className="eyebrow">INSTALLED VERSION</span><strong>{info?`v${info.currentVersion}`:loading?'Checking…':'Unavailable'}</strong><p>{info?.updateAvailable?'A newer stable release is available.':info?.latestVersion?`You’re up to date with v${info.latestVersion}.`:'Release information is unavailable.'}</p></div><div className="update-latest"><span className="muted small">LATEST RELEASE</span><strong>{info?.latestVersion?`v${info.latestVersion}`:'—'}</strong>{info?.publishedAt&&<span className="muted small">Published {new Date(info.publishedAt).toLocaleDateString()}</span>}</div></section>
  {error&&<div className="notice error" role="alert">{error}</div>}{info?.error&&<div className="notice" role="status">{info.error} {info.repository==='kavaliersdelikt/fledge'&&<span>Repository: <a href={`https://github.com/${info.repository}`} target="_blank" rel="noreferrer">{info.repository}</a>.</span>}</div>}
  <section className="section"><div className="section-title"><div><h2>Update this host</h2><p className="muted">Run the updater from the Fledge checkout on the machine running Docker Compose.</p></div><Wrench size={17}/></div><div className="update-command"><div><Terminal size={15}/> HOST COMMAND <span>{windows?'PowerShell':'Terminal'}</span></div><code>{command}</code><button className="btn" onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy command'}</button></div><div className="update-assurances"><p><ShieldCheck size={16}/> The script requires a clean Git checkout, makes a PostgreSQL dump, checks the selected release, and waits for the API and web health checks.</p><p>If health checks fail, it restores the previous application code and rebuilds. Database migrations may already have run; the SQL backup is retained for a deliberate manual recovery.</p><p>Updates run on the host because a container cannot safely replace its own Docker Compose deployment. The panel only checks releases and prepares the command; it never runs host commands.</p></div></section>
  {info?.latestVersion&&info.body&&<section className="section"><div className="section-title"><div><h2>{info.releaseName}</h2><p className="muted">Release notes from GitHub.</p></div><a className="btn" href={info.releaseUrl} target="_blank" rel="noreferrer">View release <ExternalLink size={14}/></a></div><pre className="release-notes">{info.body}</pre></section>}
  {info&&<p className="muted small update-meta">Repository: <a href={`https://github.com/${info.repository}`} target="_blank" rel="noreferrer">{info.repository}</a> · Checked {new Date(info.checkedAt).toLocaleString()}</p>}
 </>;
}
